(defvar *lesser-minor-armor*
  '(((0 . 79) "+1 item")
    ((80 . 99) *lesser-minor-spesific-armor-armor*)))

(defvar *lesser-minor-spesific-armor*
  '(((0 . 49) "Mithral shirt")
    ((50 . 99) "Masterwork/special material armor")))

(defvar *lesser-minor-shield*
  '(((0 . 79) "+1 item")
    ((80 . 99) *lesser-minor-spesific-shield*)))

(defvar *lesser-minor-spesific-shield*
  '(((0 . 19) "Living steel heavy shield")
    ((20 . 44) "Darkwood buckler")
    ((45 . 69) "Darkwood shield")
    ((70 . 99) "Mithral heavy shield")))

(defvar *lesser-minor-wonderous*
  '(((0 . 5) *lesser-minor-belts*)
    ((6 . 11) *lesser-minor-body*)
    ((12 . 16) *lesser-minor-chest*)
    ((17 . 21) *lesser-minor-eyes*)
    ((22 . 27) *lesser-minor-feet*)
    ((28 . 33) *lesser-minor-hands*)
    ((34 . 40) *lesser-minor-head*)
    ((41 . 46) *lesser-minor-headband*)
    ((47 . 53) *lesser-minor-neck*)
    ((54 . 60) *lesser-minor-shoulder*)
    ((61 . 66) *lesser-minor-wrist*)
    ((67 . 99) *lesser-minor-slotless*)))

(defvar *lesser-minor-belts*
  '(((0 . 15) "Belt of tumbling")
    ((16 . 27) "Beneficial bandolier")
    ((28 . 39) "Meridian belt")
    ((40 . 53) "Bladed belt")
    ((54 . 69) "Heavyload belt")
    ((70 . 83) "Aquatic cummerbund")
    ((84 . 99) "Equestrian belt")))

(defvar *lesser-minor-body*
  '(((0 . 19) "Robe of infinite twine")
    ((20 . 34) "Robe of needles")
    ((35 . 59) "Robe of bones")
    ((60 . 69) "Bodywrap of mighty strikes")
    ((70 . 79) "Corset of the vishkanya")
    ((80 . 99) "Druid's vestment")))

(defvar *lesser-minor-chest*
  '(((0 . 14) "Bandages of rapid recovery")
    ((15 . 29) "Quick runner's shirt")
    ((30 . 49) "Endless bandolier")
    ((50 . 74) "All tools vest")
    ((75 . 99) "Vest of surgery")))

(defvar *lesser-minor-eyes*
  '(((0 . 17) "Deathwatch eyes")
    ((18 . 37) "Eyes of the eagle")
    ((38 . 57) "Goggles of minute seeing")
    ((58 . 71) "Pirate's eye patch")
    ((72 . 86) "Spectacles of understanding")
    ((87 . 99) "Lenses of detection")))

(defvar *lesser-minor-feet*
  '(((0 . 10) "Boosts of the cat")
    ((11 . 21) "Daredevil boots")
    ((22 . 30) "Boots of the enduring march")
    ((31 . 40) "Feather step slippers")
    ((41 . 49) "Boots of friendly terrain")
    ((50 . 59) "Boots of the winterland")
    ((60 . 75) "Boots of elvenkind")
    ((76 . 84) "Acrobat slippers")
    ((85 . 91) "Horseshoes of speed")
    ((92 . 99) "Boots of the mire")))

(defvar *lesser-minor-hands*
  '(((0 . 12) "Assisting gloves")
    ((13 . 21) "Claws of the ice bear")
    ((22 . 33) "Gloves of reconnaissance")
    ((34 . 45) "Glowing glove")
    ((46 . 57) "Apprentice's cheating gloves")
    ((58 . 69) "Challenger's gloves")
    ((70 . 79) "Gloves of larceny")
    ((80 . 89) "Healer's gloves")
    ((90 . 99) "Engineer's workgloves")))

(defvar *lesser-minor-head*
  '(((0 . 9) "Mask of stony demeanor")
    ((10 . 21) "Cap of human guise")
    ((22 . 35) "Cap of light")
    ((36 . 55) "Hat of disguise")
    ((56 . 70) "Buffering cap")
    ((71 . 84) "Miser's mask")
    ((85 . 99) "Stalker's mask")))

(defvar *lesser-minor-headband*
  '(((0 . 59) "Phylactery of faithfulness")
    ((60 . 99) "Deadman's headband")))

(defvar *lesser-minor-neck*
  '(((0 . 9) "Hand of the mage")
    ((10 . 17) "Aegis of recovery")
    ((18 . 24) "Amulet of bullet protection")
    ((25 . 36) "Brooch of shielding")
    ((37 . 48) "Necklace of fireballs (T-1)")
    ((49 . 62) "Amulet of natural armor +1")
    ((63 . 71) "Golembane scarab")
    ((72 . 81) "Necklace of fireballs (T-2)")
    ((82 . 88) "Swarmbane clasp")
    ((89 . 94) "Mind sentinel medallion")
    ((95 . 99) "Mummer's ruff")))

(defvar *lesser-minor-shoulder*
  '(((0 . 5) "Catching cape")
    ((6 . 9) "Cloak of human guise")
    ((10 . 29) "Cloak of resistance +1")
    ((30 . 35) "Muleback cords")
    ((36 . 37) "Shawl of life-keeping")
    ((38 . 43) "Shield cloak")
    ((44 . 49) "Quickchange cloak")
    ((50 . 55) "Cowardly crouching cloak")
    ((56 . 73) "Cloak of elvenkind")
    ((74 . 79) "Cloak of the hedge wizard")
    ((80 . 84) "Cloak of fiery vanishing")
    ((85 . 93) "Cloak of fangs")
    ((94 . 96) "Pauldrons of the serpent")
    ((97 . 99) "Stonemist cloak")))

(defvar *lesser-minor-wrist*
  '(((0 . 9) "Sleeves of many garments")
    ((10 . 19) "Armbands of the brawler")
    ((20 . 47) "Bracer's of armor +1")
    ((48 . 62) "Burglar's bracers")
    ((63 . 90) "Bracers of steadiness")
    ((91 . 95) "Manacles of cooperation")
    ((96 . 99) "Shackles of complaiance")))

(defvar *lesser-minor-slotless*
  '((0 "Feather token (anchor)")
    (1 "Universal solvent")
    ((2 . 3) "Ioun torch")
    (4 "Stubborn nail")
    (5 "War paint of the terrible visage")
    (6 "Elixir of love")
    (7 "Unguent of timelessness")
    (8 "Feather token (fan)")
    (9 "Formula alembic")
    (10 "Hybridization funnel")
    (11 "Soul soap")
    (12 "Dust of tracelessness")
    ((13 . 15) "Elixir of hiding")
    ((16 . 18) "Elixir of swimming")
    ((19 . 21) "Elixir of tumbling")
    ((22 . 24) "Elixir of vision")
    ((25 . 26) "Nightdrops")
    (27 "Oil of silence")
    ((28 . 30) "Silversheen")
    (31 "Traveler's any-tool")
    ((32 . 33) "Bottle of messages")
    ((34 . 35) "Feather token (bird)")
    (36 "Origami swarm")
    (37 "Alluring golden apple")
    (38 "Feather token (tree)")
    (39 "Key of lock jamming")
    ((40 . 41) "Feather token (swan boat)")
    (42 "Animated portrait")
    (43 "Bottled misfortune")
    ((44 . 45) "Elixir of truth")
    ((46 . 47) "Feather token (whip)")
    ((48 . 50) "Scabbard of honing")
    ((51 . 52) "Seer's tea")
    ((53 . 56) "Abjurant salt")
    ((57 . 60) "Arrow magnet")
    ((61 . 62) "Dust of darkness")
    ((63 . 68) "Campfire bead")
    ((69 . 71) "Archon's torch")
    ((72 . 74) "Book of extended summoning (lesser)")
    ((75 . 78) "Iron rope")
    ((79 . 82) "Snapleaf")
    ((83 . 85) "Bottled yeti fur")
    ((86 . 88) "Defoliant polish")
    ((89 . 91) "Dust of emulation")
    ((92 . 96) "Steadfast gut-stone")
    ((97 . 99) "Dust of dryness")))

(defvar *minor-potion-generic*
  '(((0 . 19) "Cantrip potion")
    ((20 . 59) "First level potion")
    ((60 . 99) "Second level potion")))

(defvar *minor-potion-spesific*
  '(((0 . 9) "Cure light wonds")
    ((10 . 12) "Endure elements")
    ((13 . 14) "Hide from animals")
    ((15 . 16) "Hide from undead")
    ((17 . 18) "Jump")
    ((19 . 21) "Mage armor")
    ((22 . 24) "Magic fang")
    (25 "Magic stone")
    ((26 . 28) "Magic weapon")
    (29 "Pass without trace")
    ((30 . 31) "Protection from (Alignment)")
    ((32 . 33) "Remove fear")
    (34 "Sanctuary")
    ((35 . 37) "Shield of faith +2")
    (38 "Shillelagh")
    ((39 . 40) "Bless weapon")
    ((41 . 43) "Enlarge person")
    (44 "Reduce person")
    ((45 . 46) "Aid")
    ((47 . 49) "Barkskin +2")
    ((50 . 52) "Bear's endurance")
    ((53 . 55) "Blur")
    ((56 . 58) "Bull's strength")
    ((59 . 61) "Cat's grace")
    ((62 . 66) "Cure moderate wounds")
    (67 "Darkness")
    ((68 . 70) "Darkvision")
    ((71 . 73) "Delay poison")
    ((74 . 75) "Eagle's splendor")
    ((76 . 77) "Fox's cunning")
    ((78 . 80) "Invisibility")
    ((81 . 83) "Lesser restoration")
    ((84 . 85) "Levitate")
    (86 "Misdirection")
    ((87 . 88) "Owl's wisdom")
    ((89 . 90) "Protection from arrows (30)")
    ((91 . 92) "Remove paralysis")
    ((93 . 95) "Resist energy (random) (10)")
    (96 "Shield of faith +3")
    ((97 . 98) "Spider climb")
    (99 "Undetectable alignment")))

(defvar *minor-scroll*
  '(((0 . 4) "Cantrip")
    ((5 . 49) "First level")
    ((50 . 94) "Second level")
    ((95 . 99) "Third level")))

(defvar *lesser-minor-ring*
  '(((0 . 6) "Prisoner's dungeon ring")
    ((7 . 15) "Ring of arcane signets")
    ((16 . 24) "Ring of spell knowledge I")
    ((25 . 39) "Ring of protection")
    ((40 . 46) "Ring of the grasping grave")
    ((47 . 56) "Ring of feather falling")
    ((57 . 65) "Ring of climbing")
    ((66 . 74) "Ring of jumping")
    ((75 . 83) "Ring of sustenance")
    ((84 . 92) "Ring of swimming")
    ((93 . 99) "Ring of ferocious action")))

(defvar *minor-wand*
  '(((0 . 4) "Cantrip")
    ((5 . 59) "First level")
    ((60 . 99) "Second level")))

(defvar *lesser-minor-weapon*
  '(((0 . 79) "+1 weapon")
    ((80 . 99) *lesser-minor-spesific-weapon*)))

(defvar *lesser-minor-spesific-weapon*
  '(((0 . 1) "Tracer bullet")
    ((2 . 7) "Sleepp arrow")
    ((8 . 9) "Dustburst bullet")
    ((10 . 15) "Tangle bolt")
    ((16 . 21) "Screaming bolt")
    ((22 . 31) "Masterwork silver dagger")
    ((32 . 33) "Alchemist's bullet")
    ((34 . 43) "Cold iron masterwork longsword")
    ((44 . 49) "Hushing arrow")
    ((50 . 55) "Hushing arrow (greater)")
    ((56 . 65) "Javelin of lightning")
    ((66 . 73) "Searing arrow")
    ((74 . 81) "Sizzling arrow")
    ((82 . 83) "Burrowing bullet (lesser)")
    ((84 . 91) "Dust bolt")
    ((92 . 99) "Slaying arrow")))

(defvar *greater-minor-weapon*
  '(((0 . 25) "+1 weapon")
    ((26 . 52) "+2 weapon")
    ((53 . 79) "+1 one and" *plus-one-weapon*)
    ((80 . 99) *greater-minor-spesific-weapon*)))

(defvar *plus-one-weapon*
  '(((0 . 49) *plus-one-melee*)
    ((50 . 74) *plus-one-range*)
    ((75 . 99) *plus-one-ammo*)))

(defvar *greater-minor-spesific-weapon*
  '(((0 . 19) "Adamantine dagger")
    ((20 . 39) "Adamantine battleaxe")
    ((40 . 49) "Burrowing bullet (greater)")
    ((50 . 69) "Slaying arrow (greater)")
    ((70 . 79) "Lance of jousting")
    ((80 . 99) "Shatterspike")))

(defvar *plus-one-melee*
  '((0 "Impervious")
    (1 "Glamered")
    (2 "Allying")
    ((3 . 7) "Bane")
    (8 "Benevolent")
    (9 "Called")
    ((10 . 11) "Conductive")
    ((12 . 15) "Corrosive")
    (16 "Countering")
    (17 "Courageous")
    (18 "Cruel")
    ((19 . 20) "Cunning")
    (21 "Deadly")
    ((22 . 25) "Defending")
    (26 "Dispelling")
    ((27 . 32) "Flaming")
    ((33 . 38) "Frost")
    ((39 . 40) "Furious")
    ((41 . 44) "Ghost touch")
    ((45 . 46) "Grayflame")
    (47 "Grounding")
    (48 "Guardian")
    (49 "Heartseeker")
    ((50 . 51) "Huntsman")
    ((52 . 53) "Jurist")
    ((54 . 58) "Keen")
    ((59 . 60) "Ki focus")
    (61 "Limning")
    ((62 . 63) "Menacing")
    (64 "Merciful")
    ((65 . 67) "Mighty cleaving")
    (68 "Mimetic")
    (69 "Neutralizing")
    (70 "Ominous")
    (71 "Planer")
    (72 "Quenching")
    (73 "Seaborne")
    ((74 . 79) "Shock")
    ((80 . 84) "Spell storing")
    (85 "Thawing")
    ((86 . 90) "Throwing")
    ((91 . 95) "Thundering")
    (96 "Valiant")
    ((98 . 99) "Vicious")))

(defvar *plus-one-range*
  '((0 "Adaptive")
    (1 "Impervious")
    (2 "Glamered")
    ((3 . 5) "Allying")
    ((6 . 14) "Bane")
    (15 "Called")
    ((16 . 18) "Conductive")
    (19 "Conserving")
    ((20 . 23) "Corrosive")
    (24 "Cruel")
    ((25 . 27) "Cunning")
    ((28 . 35) "Distance")
    ((36 . 44) "Flaming")
    ((45 . 53) "Frost")
    ((54 . 57) "Huntsman")
    ((58 . 61) "Jurist")
    (62 "Limning")
    (63 "Lucky")
    ((64 . 65) "Merciful")
    (66 "Planer")
    (67 "Reliable")
    ((68 . 75) "Returning")
    ((76 . 83) "Seeking")
    ((84 . 91) "Shock")
    ((92 . 99) "Thundering")))

(defvar *plus-one-ammo*
  '(((0 . 4) "Dry load")
    ((5 . 15) "Bane")
    (16 "Conductive")
    ((17 . 27) "Corrosive")
    (28 "Cruel")
    (29 "Cunning"
    ((30 . 42) "Flaming")
    ((43 . 55) "Frost")
    ((56 . 63) "Ghost touch")
    (64 "Limning")
    ((65 . 66) "Merciful")
    (67 "Planer")
    ((68 . 72) "Seeking")
    ((73 . 85) "Shock")
    ((86 . 99) "Thundering"))))

(defvar *greater-minor-armor*
  '(((0 . 25) "+1 armor")
    ((26 . 52) "+2 armor")
    ((53 . 79) "+1 armor and" *plus-one-armor*)
    ((80 . 99) *greater-minor-spesific-armor*)))

(defvar *plus-one-armor*
  '(((0 . 5) "Benevolent")
    ((6 . 11) "Poison resistant")
    ((12 . 17) "Balanced")
    ((18 . 23) "Bitter")
    ((24 . 29) "Bolstering")
    ((30 . 35) "Brawling")
    ((36 . 41) "Champion")
    ((42 . 47) "Dastard")
    ((48 . 53) "Deathless")
    ((54 . 59) "Defiant")
    ((60 . 65) "Fortification (light)")
    ((66 . 70) "Grinding")
    ((71 . 75) "Impervious")
    ((76 . 81) "Mirrored")
    ((82 . 87) "Spell storing")
    ((88 . 93) "Stanching")
    ((94 . 99) "Warding")))

(defvar *greater-minor-spesific-armor*
  '(((0 . 32) "Mistmail")
    ((33 . 65) "Otyugh hide")
    ((66 . 99) "Dragonhide plate")))

(defvar *greater-minor-shield*
  '(((0 . 25) "+1 shield")
    ((26 . 52) "+2 shield")
    ((53 . 79) "+1 shield and" *plus-one-shield*)
    ((80 . 99) *greater-minor-spesific-shield*)))

(defvar *plus-one-shield*
  '(((0 . 9) "Poison resistant")
    ((10 . 18) "Arror catching")
    ((19 . 27) "Bashing")
    ((28 . 36) "Blinding")
    ((37 . 45) "Clangorous")
    ((56 . 54) "Defiant")
    ((55 . 63) "Fortification (light)")
    ((64 . 72) "Grinding")
    ((73 . 81) "Impervious")
    ((82 . 90) "Mirrored")
    ((91 . 99) "Ramming")))

(defvar *greater-minor-spesific-shield*
  '(((0 . 29) "Zombie skin shield")
    ((30 . 74) "Caster's shield")
    ((75 . 99) "Burglar's buckler")))

(defvar *greater-minor-ring*
  '(((0 . 14) "Ring of counterspell")
    ((15 . 24) "Ring of maniacal devices")
    ((25 . 34) "Ring of rat fangs")
    ((35 . 51) "Ring of sacred mistletoe")
    ((52 . 68) "Ring of spell knowledge II")
    ((69 . 85) "Ring of swarming stabs")
    ((86 . 99) "Ring of grit mastery")))

(defvar *greater-minor-wonderous*
  '(((0 . 5) *greater-minor-belts*)
    ((6 . 11) *greater-minor-body*)
    ((12 . 16) *greater-minor-chest*)
    ((17 . 21) *greater-minor-eyes*)
    ((22 . 27) *greater-minor-feet*)
    ((28 . 33) *greater-minor-hands*)
    ((34 . 40) *greater-minor-head*)
    ((41 . 46) *greater-minor-headband*)
    ((47 . 53) *greater-minor-neck*)
    ((54 . 60) *greater-minor-shoulder*)
    ((61 . 66) *greater-minor-wrist*)
    ((67 . 99) *greater-minor-slotless*)))


(defun rand-treas (hoard)
  (let ((num (random 100)))
    (labels ((select (this rest)
                (if (or (<= (car (car this)) num (cdr (car this)))
                        (null rest))
                    (cdr this)
                    (select (car rest) (cdr rest)))))
      (select (car hoard) (cdr hoard)))))

(defvar *treasure*
  '(((0 . 29) "Zombie skin shield")
    ((30 . 74) "Caster's shield")
    ((75 . 99) "Burglar's buckler")))
