(in-package :treasure-gen)

(defvar *lesser-minor-ring*
  '(((0 . 6) "Prisoner's dungeon ring")
    ((7 . 15) "Ring of arcane signets")
    ((16 . 24) "Ring of spell knowledge I")
    ((25 . 39) "Ring of protection")
    ((40 . 46) "Ring of the grasping grave")
    ((47 . 56) "Ring of feather falling")
    ((57 . 65) "Ring of climbing")
    ((66 . 74) "Ring of jumping")
    ((75 . 83) "Ring of sustenance")
    ((84 . 92) "Ring of swimming")
    ((93 . 99) "Ring of ferocious action")))
;
(defvar *greater-minor-ring*
  '(((0 . 14) "Ring of counterspell")
    ((15 . 24) "Ring of maniacal devices")
    ((25 . 34) "Ring of rat fangs")
    ((35 . 51) "Ring of sacred mistletoe")
    ((52 . 68) "Ring of spell knowledge II")
    ((69 . 85) "Ring of swarming stabs")
    ((86 . 99) "Ring of grit mastery")))

(defvar *lesser-medium-ring*
  '(((0 . 1) "Ring of forcefangs")
    ((2 . 5) "Ring of mind shielding")
    ((6 . 10) "Ring of protection +2")
    ((11 . 12) "Ring of strength sapping")
    ((13 . 16) "Ring of force shield")
    ((17 . 21) "Ring of the ram")
    ((22 . 23) "Scholar’s ring")
    ((24 . 26) "Ring of climbing (improved)")
    ((27 . 28) "Ring of curing")
    ((29 . 30) "Ring of foe focus")
    ((31 . 34) "Ring of jumping (improved)")
    ((35 . 36) "Ring of ki mastery")
    ((37 . 39) "Ring of revelation (lesser)")
    ((40 . 42) "Ring of swimming (improved)")
    ((43 . 45) "Ring of animal friendship")
    ((46 . 47) "Ring of transposition")
    ((48 . 49) "Ring of tactical precision")
    ((50 . 51) "Ring of the sophisticate")
    ((52 . 54) "Decoy ring")
    ((55 . 57) "Ring of craft magic")
    ((58 . 60) "Ring of ectoplasmic invigoration")
    ((61 . 63) "Ring of energy resistance (minor)")
    ((64 . 66) "Ring of the troglodyte")
    ((67 . 69) "Steelhand circle")
    ((70 . 75) "Ring of chameleon power")
    ((76 . 78) "Ring of spell knowledge III")
    ((79 . 81) "Ring of the sea strider")
    ((82 . 84) "Ring of retribution")
    ((85 . 88) "Ring of water walking")
    ((89 . 94) "Dungeon ring (jailer’s)")
    ((95 . 99) "Ring of revelation (greater)")))

(defvar *greater-medium-ring*
  '(((0 . 3) "Ring of inner fortitude (minor)")
    ((4 . 15) "Ring of protection +3")
    ((16 . 25) "Ring of spell storing (minor)")
    ((26 . 29) "Ring of energy shroud")
    ((30 . 34) "Ring of arcane mastery")
    ((35 . 45) "Ring of invisibility")
    ((46 . 53) "Ring of wizardry I")
    ((54 . 59) "Ring of revelation (superior)")
    ((60 . 67) "Ring of spell knowledge IV")
    ((68 . 79) "Ring of evasion")
    ((80 . 87) "Ring of x-ray vision")
    ((88 . 99) "Ring of blinking")))


(defvar *lesser-major-ring*
  '(((0 . 8) "Ring of energy resistance (major)")
    ((9 . 15) "Ring of the ecclesiarch")
    ((16 . 32) "Ring of protection +4")
    ((33 . 38) "Ring of return")
    ((39 . 54) "Ring of freedom of movement")
    ((55 . 69) "Ring of wizardry II")
    ((70 . 74) "Ring of inner fortitude (major)")
    ((75 . 91) "Ring of energy resistance (greater)")
    ((92 . 99) "Ring of delayed doom")))

(defvar *greater-major-ring*
  '(((0 . 5) "Ring of friend shield")
    ((6 . 17) "Ring of protection +5")
    ((18 . 26) "Ring of shooting stars")
    ((27 . 36) "Ring of spell storing")
    ((37 . 42) "Ring of continuation")
    ((43 . 47) "Ring of inner fortitude (greater)")
    ((48 . 56) "Ring of wizardry III")
    ((57 . 62) "Spiritualist Rings")
    ((63 . 70) "Ring of telekinesis")
    ((71 . 75) "Ring of regeneration")
    ((76 . 81) "Ring of spell turning")
    ((82 . 85) "Ring of wizardry IV")
    ((86 . 89) "Ring of three wishes")
    ((90 . 92) "Ring of djinni calling")
    ((93 . 96) "Ring of elemental command")
    ((97 . 99) "Ring of spell storing (major)")))
