(in-package :treasure-gen)

(defvar *lesser-medium-rod*
  '((0 "Metamagic, merciful, minor")
    ((1 . 33) "Metamagic (minor)" *meta-lvl-one*)
    ((34 . 48) "Immovable rod")
    ((49 . 58) "Rod of thunderous force")
    (59 "Metamagic, merciful, normal")
    (60 "Rod of ice")
    ((61 . 70) "Metamagic (minor)" *meta-lvl-two*)
    ((71 . 80) "Rod of metal and mineral detection")
    ((81 . 85) "Metamagic (normal)" *meta-lvl-one*)
    ((86 . 99) "Rod of cancellation")))

(defvar *greater-medium-rod*
  '(((0 . 2) "Conduit rod")
    ((3 . 5) "Grounding rod")
    ((6 . 9) "Rod of the wayang")
    ((10 . 17) "Rod of wonder")
    (18 "Metamagic, merciful, greater")
    ((19 . 28) "Rod of the python")
    ((29 . 32) "Trap-stealer’s rod")
    ((33 . 54) "Metamagic (minor)" *meta-lvl-three*)
    ((55 . 58) "Rod of balance")
    ((59 . 62) "Rod of escape")
    ((63 . 71) "Rod of flame extinguishing")
    ((72 . 75) "Rod of ruin")
    ((76 . 79) "Sapling rod")
    ((80 . 85) "Rod of beguiling")
    ((86 . 89) "Rod of nettles")
    ((90 . 99) "Rod of the viper")))

(defvar *lesser-major-rod*
  '(((0 . 3) "Suzerain scepter")
    ((4 . 5) "Fiery nimbus rod")
    ((6 . 12) "Rod of enemy detection")
    ((13 . 26) "Metamagic (greater)" *meta-lvl-one*)
    ((27 . 35) "Rod of splendor")
    ((36 . 43) "Rod of withering")
    ((44 . 49) "Earthbind rod")
    ((50 . 55) "Rod of the aboleth")
    ((56 . 62) "Liberator’s rod")
    ((63 . 69) "Metamagic (normal)" *meta-lvl-two*)
    ((70 . 78) "Rod of thunder and lightning")
    ((79 . 82) "Metamagic, quicken, minor")
    ((83 . 93) "Rod of negation")
    ((94 . 99) "Rod of steadfast resolve")))

(defvar *greater-major-rod*
  '(((0 . 7) "Rod of absorption")
    ((8 . 10) "Rod of flailing")
    ((11 . 25) "Metamagic (normal)" *meta-lvl-three*)
    ((26 . 27) "Rod of rulership")
    ((28 . 29) "Rod of security")
    ((30 . 31) "Rod of shadows")
    ((32 . 33) "Rod of mind mastery")
    ((34 . 36) "Rod of lordly might")
    ((37 . 56) "Metamagic (greater)" *meta-lvl-two*)
    (57 "Scepter of heaven")
    ((58 . 67) "Metamagic, quicken, normal")
    ((68 . 69) "Rod of dwarven might")
    ((70 . 74) "Rod of alertness")
    ((75 . 94) "Metamagic (greater)" *meta-lvl-three*)
    ((95 . 99) "Metamagic, quicken, greater")))

(defvar *meta-lvl-one*
  '(((0 . 3) "Bouncing Spell")
    ((4 . 8) "Disruptive Spell")
    ((9 . 13) "Ectoplasmic Spell")
    ((14 . 18) "Elemental Spell")
    ((19 . 30) "Enlarge Spell")
    ((31 . 42) "Extend Spell")
    ((43 . 47) "Flaring Spell")
    ((48 . 52) "Focused Spell")
    ((53 . 57) "Intensified Spell")
    ((58 . 62) "Lingering Spell")
    ((63 . 67) "Piercing Spell")
    ((68 . 72) "Reach Spell")
    ((73 . 77) "Rime Spell")
    ((78 . 82) "Selective Spell")
    ((83 . 94) "Silent Spell")
    ((95 . 99) "Toppling Spell")))

(defvar *meta-lvl-two*
  '(((0 . 10) "Burning Spell")
    ((11 . 21) "Concussive Spell")
    ((22 . 39) "Empower Spell")
    ((40 . 50) "Persistent Spell")
    ((51 . 61) "Sickening Spell")
    ((62 . 74) "Thanatopic Spell")
    ((75 . 87) "Threnodic Spell")
    ((88 . 99) "Thundering Spell")))

(defvar *meta-lvl-three*
  '(((0 . 19) "Dazing Spell")
    ((20 . 39) "Echoing Spell")
    ((40 . 69) "Maximize Spell")
    ((70 . 99) "Widen Spell")))
