(in-package :treasure-gen)

(defvar *lesser-minor-scroll*
  '(((0 . 14) *lvl-zero-scroll*)
    ((15 . 94) *lvl-one-scroll*)
    ((95 . 99) *lvl-two-scroll*)))
;
(defvar *greater-minor-scroll*
  '(((0 . 4) *lvl-zero-scroll*)
    ((5 . 34) *lvl-one-scroll*)
    ((35 . 89) *lvl-two-scroll*)
    ((90 . 99) *lvl-three-scroll*)))

(defvar *lesser-medium-scroll*
  '(((0 . 9) *lvl-two-scroll*)
    ((10 . 54) *lvl-three-scroll*)
    ((55 . 99) *lvl-four-scroll*)))

(defvar *greater-medium-scroll*
  '(((0 . 19) *lvl-three-scroll*)
    ((20 . 59) *lvl-four-scroll*)
    ((60 . 99) *lvl-five-scroll*)))

(defvar *lesser-major-scroll*
  '(((0 . 29) *lvl-four-scroll*)
    ((30 . 64) *lvl-five-scroll*)
    ((65 . 89) *lvl-six-scroll*)
    ((90 . 99) *lvl-seven-scroll*)))

(defvar *greater-major-scroll*
  '(((0 . 4) *lvl-six-scroll*)
    ((5 . 34) *lvl-seven-scroll*)
    ((35 . 69) *lvl-eight-scroll*)
    ((70 . 99) *lvl-nine-scroll*)))

(defvar *lvl-zero-scroll*
  '(((0 . 44) *CA-lvl-zero-scroll*)
    ((45 . 59) *UA-lvl-zero-scroll*)
    ((60 . 89) *CD-lvl-zero-scroll*)
    ((90 . 99) *UD-lvl-zero-scroll*)))

(defvar *lvl-one-scroll*
  '(((0 . 44) *CA-lvl-one-scroll*)
    ((45 . 59) *UA-lvl-one-scroll*)
    ((60 . 89) *CD-lvl-one-scroll*)
    ((90 . 99) *UD-lvl-one-scroll*)))

(defvar *lvl-two-scroll*
  '(((0 . 44) *CA-lvl-two-scroll*)
    ((45 . 59) *UA-lvl-two-scroll*)
    ((60 . 89) *CD-lvl-two-scroll*)
    ((90 . 99) *UD-lvl-two-scroll*)))

(defvar *lvl-three-scroll*
  '(((0 . 44) *CA-lvl-three-scroll*)
    ((45 . 59) *UA-lvl-three-scroll*)
    ((60 . 89) *CD-lvl-three-scroll*)
    ((90 . 99) *UD-lvl-three-scroll*)))

(defvar *lvl-four-scroll*
  '(((0 . 44) *CA-lvl-four-scroll*)
    ((45 . 59) *UA-lvl-four-scroll*)
    ((60 . 89) *CD-lvl-four-scroll*)
    ((90 . 99) *UD-lvl-four-scroll*)))

(defvar *lvl-five-scroll*
  '(((0 . 44) *CA-lvl-five-scroll*)
    ((45 . 59) *UA-lvl-five-scroll*)
    ((60 . 89) *CD-lvl-five-scroll*)
    ((90 . 99) *UD-lvl-five-scroll*)))

(defvar *lvl-six-scroll*
  '(((0 . 44) *CA-lvl-six-scroll*)
    ((45 . 59) *UA-lvl-six-scroll*)
    ((60 . 89) *CD-lvl-six-scroll*)
    ((90 . 99) *UD-lvl-six-scroll*)))

(defvar *lvl-seven-scroll*
  '(((0 . 44) *CA-lvl-seven-scroll*)
    ((45 . 59) *UA-lvl-seven-scroll*)
    ((60 . 89) *CD-lvl-seven-scroll*)
    ((90 . 99) *UD-lvl-seven-scroll*)))

(defvar *lvl-eight-scroll*
  '(((0 . 44) *CA-lvl-eight-scroll*)
    ((45 . 59) *UA-lvl-eight-scroll*)
    ((60 . 89) *CD-lvl-eight-scroll*)
    ((90 . 99) *UD-lvl-eight-scroll*)))

(defvar *lvl-nine-scroll*
  '(((0 . 44) *CA-lvl-nine-scroll*)
    ((45 . 59) *UA-lvl-nine-scroll*)
    ((60 . 89) *CD-lvl-nine-scroll*)
    ((90 . 99) *UD-lvl-nine-scroll*)))

;Common Arcane

(defvar *CA-lvl-zero-scroll*
  '(((0 . 8) "Acid splash (arcane)")
    ((9 . 16) "Daze (arcane)")
    ((17 . 26) "Detect magic (arcane)")
    ((27 . 34) "Flare (arcane)")
    ((35 . 44) "Light (arcane)")
    ((45 . 54) "Mending (arcane)")
    ((55 . 62) "Prestidigitation (arcane)")
    ((63 . 80) "Ray of frost (arcane)")
    ((81 . 90) "Read magic (arcane)")
    ((91 . 99) "Touch of fatigue (arcane)")))

(defvar *CA-lvl-one-scroll*
  '(((0 . 4) "Burning hands (arcane)")
    ((5 . 8) "Cause fear (arcane)")
    ((9 . 13) "Charm person (arcane)")
    ((14 . 16) "Chill touch (arcane)")
    ((17 . 20) "Disguise self (arcane)")
    ((21 . 23) "Endure elements (arcane)")
    ((24 . 27) "Enlarge person (arcane)")
    ((28 . 31) "Expeditious retreat (arcane)")
    ((32 . 35) "Grease (arcane)")
    ((36 . 38) "Hypnotism (arcane)")
    ((39 . 41) "Identify (arcane)")
    ((42 . 47) "Mage armor (arcane)")
    ((48 . 53) "Magic missile (arcane)")
    ((54 . 57) "Magic weapon (arcane)")
    ((58 . 61) "Obscuring mist (arcane)")
    ((62 . 63) "Protection from chaos (arcane)")
    ((64 . 66) "Protection from evil (arcane)")
    ((67 . 68) "Protection from good (arcane)")
    ((69 . 70) "Protection from law (arcane)")
    ((71 . 74) "Ray of enfeeblement (arcane)")
    ((75 . 79) "Shield (arcane)")
    ((80 . 83) "Shocking grasp (arcane)")
    ((84 . 87) "Silent image (arcane)")
    ((88 . 92) "Sleep (arcane)")
    ((93 . 95) "Summon monster I (arcane)")
    ((96 . 99) "True strike (arcane)")))

(defvar *CA-lvl-two-scroll*
  '(((0 . 3) "Acid arrow (arcane)")
    ((4 . 6) "Alter self (arcane)")
    ((7 . 11) "Bear's endurance (arcane)")
    ((12 . 14) "Blur (arcane)")
    ((15 . 19) "Bull's strength (arcane)")
    ((20 . 23) "Cat's grace (arcane)")
    ((24 . 26) "Darkness (arcane)")
    ((27 . 29) "Darkvision (arcane)")
    ((30 . 33) "Eagle's splendor (arcane)")
    ((34 . 36) "False life (arcane)")
    ((37 . 39) "Flaming sphere (arcane)")
    ((40 . 43) "Fox's cunning (arcane)")
    ((44 . 46) "Glitterdust (arcane)")
    ((47 . 51) "Invisibility (arcane)")
    ((52 . 53) "Knock (arcane)")
    ((54 . 57) "Levitate (arcane)")
    ((58 . 60) "Minor image (arcane)")
    ((61 . 64) "Mirror image (arcane)")
    ((65 . 68) "Owl's wisdom (arcane)")
    ((69 . 72) "Resist energy (arcane)")
    ((73 . 74) "Rope trick (arcane)")
    ((75 . 79) "Scorching ray (arcane)")
    ((80 . 82) "See invisibility (arcane)")
    ((83 . 84) "Shatter (arcane)")
    ((85 . 87) "Spider climb (arcane)")
    ((88 . 90) "Summon monster II (arcane)")
    ((91 . 92) "Summon swarm (arcane)")
    ((93 . 97) "Web (arcane)")
    ((98 . 99) "Wispering wind (arcane)")))

(defvar *CA-lvl-three-scroll*
  '(((0 . 2) "Beast shape (arcane)")
    ((3 . 6) "Blink (arcane)")
    ((7 . 11) "Dispel magic (arcane)")
    ((12 . 15) "Displacement (arcane)")
    ((16 . 20) "Fireball (arcane)")
    ((21 . 23) "Flame arrow (arcane)")
    ((24 . 28) "Fly (arcane)")
    ((29 . 31) "Gaseous form (arcane)")
    ((32 . 36) "Haste (arcane)")
    ((37 . 39) "Heroism (arcane)")
    ((40 . 42) "Hold person (arcane)")
    ((43 . 45) "Invisibility sphere (arcane)")
    ((46 . 50) "Lightning bolt (arcane)")
    ((51 . 53) "Magic circle against chaos (arcane)")
    ((54 . 56) "Magic circle against evil (arcane)")
    ((57 . 59) "Magic circle against good (arcane)")
    ((60 . 62) "Magic circle against law (arcane)")
    ((63 . 65) "Major image (arcane)")
    ((66 . 69) "Phantom steed (arcane)")
    ((70 . 73) "Protection from energy (arcane)")
    ((74 . 77) "Slow (arcane)")
    ((78 . 80) "Stinking doud (arcane)")
    ((81 . 83) "Suggestion (arcane)")
    ((84 . 86) "Summon monster III (arcane)")
    ((87 . 89) "Tiny hut (arcane)")
    ((90 . 93) "Tongues (arcane)")
    ((94 . 96) "Vampiric touch (arcane)")
    ((97 . 99) "Water breathing (arcane)")))

(defvar *CA-lvl-four-scroll*
  '(((0 . 2) "Beast shape II (arcane)")
    ((3 . 4) "Bestow curse (arcane)")
    ((5 . 8) "Black tentacles (arcane)")
    ((9 . 13) "Charm monster (arcane)")
    ((14 . 17) "Confusion (arcane)")
    ((18 . 20) "Crushing despair (arcane)")
    ((21 . 25) "Dimension door (arcane)")
    ((26 . 28) "Dimensional anchor (arcane)")
    ((29 . 31) "Elemental body I (arcane)")
    ((32 . 35) "Enervation (arcane)")
    ((36 . 37) "Enlarge person (mass) (arcane)")
    ((38 . 42) "Fear (arcane)")
    ((43 . 46) "Fire shield (arcane)")
    ((47 . 49) "Globe of invulnerability (lesser) (arcane)")
    ((50 . 53) "Ice storm (arcane)")
    ((54 . 58) "Invisibility (greater) (arcane)")
    ((59 . 63) "Phantasmal killer (arcane)")
    ((64 . 66) "Resilient sphere (arcane)")
    ((67 . 70) "Scrying (arcane)")
    ((71 . 73) "Shadow conjuration (arcane)")
    ((74 . 75) "Shout (arcane)")
    ((76 . 77) "Solid fog (arcane)")
    ((78 . 79) "Stone shape (arcane)")
    ((80 . 82) "Summon monster IV (arcane)")
    ((83 . 87) "Wall of fire (arcane)")
    ((88 . 91) "Wall of ice (arcane)")
    ((92 . 96) "Stoneskin (arcane)")
    ((97 . 99) "Animate dead (arcane)")))

(defvar *CA-lvl-five-scroll*)

(defvar *CA-lvl-six-scroll*)

(defvar *CA-lvl-seven-scroll*)

(defvar *CA-lvl-eight-scroll*)

(defvar *CA-lvl-nine-scroll*)

;Uncommon Arcane

(defvar *UA-lvl-zero-scroll*
  '(((0 . 6) "Arcane mark (arcane)")
    ((7 . 16) "Bleed (arcane)")
    ((17 . 24) "Dancing lights (arcane)")
    ((25 . 34) "Detect poison (arcane)")
    ((35 . 41) "Disrupt undead (arcane)")
    ((42 . 50) "Ghost sound (arcane)")
    ((51 . 60) "Message (arcane)")
    ((61 . 67) "Open/close (arcane)")
    ((68 . 74) "Resistance (arcane)")
    ((75 . 82) "Sift (arcane)")
    ((83 . 91) "Spark (arcane)")
    ((92 . 99) "Unwitting ally (arcane)")))

(defvar *UA-lvl-one-scroll*
  '(((0 . 1) "Air bubble (arcane)")
    ((2 . 5) "Alarm (arcane)")
    ((6 . 7) "Animate rope (arcane)")
    ((8 . 11) "Ant haul (arcane)")
    ((12 . 14) "Blend (arcane)")
    ((15 . 17) "Break (arcane)")
    ((18 . 22) "Color spray (arcane)")
    ((23 . 25) "Comprehend languages (arcane)")
    ((26 . 29) "Corrosive touch (arcane)")
    ((30 . 32) "Detect secret doors (arcane)")
    ((33 . 35) "Detect undead (arcane)")
    ((36 . 37) "Erase (arcane)")
    ((38 . 39) "Flare burst (arcane)")
    ((40 . 42) "Floating disk (arcane)")
    ((43 . 45) "Hold portal (arcane)")
    ((46 . 47) "Hydraulic push (arcane)")
    ((48 . 50) "Icide dagger (arcane)")
    ((51 . 53) "Isslusion of calm (arcane)")
    ((54 . 57) "Jump (arcane)")
    ((58 . 59) "Magic aura (arcane)")
    ((60 . 62) "Mirror strike (arcane)")
    ((63 . 65) "Mount (arcane)")
    ((66 . 68) "Ray of striking (arcane)")
    ((69 . 70) "Reduce person (arcane)")
    ((71 . 73) "Shadow weapon (arcane)")
    ((74 . 76) "Shock shield (arcane)")
    ((77 . 79) "Stone fist (arcane)")
    ((80 . 83) "Touch of the sea (arcane)")
    ((84 . 87) "Unseen servant (arcane)")
    ((88 . 90) "Urban grace (arcane)")
    ((91 . 95) "Vanish (arcane)")
    ((96 . 97) "Ventriloquism (arcane)")
    ((98 . 99) "Voice alteration (arcane)")))

(defvar *UA-lvl-two-scroll*
  '(((0 . 2) "Bestow weapon proficiency (arcane)")
    ((3 . 5) "Blindness/deafness (arcane)")
    ((6 . 8) "Burning gaze (arcane)")
    ((9 . 11) "Certain grip (arcane)")
    ((12 . 13) "Command undead (arcane)")
    ((14 . 15) "Create pit (arcane)")
    ((16 . 19) "Daze monster (arcane)")
    ((20 . 22) "Detect thoughts (arcane)")
    ((23 . 26) "Disguise other (arcane)")
    ((27 . 30) "Elemental touch (arcane)")
    ((31 . 33) "Fire breath (arcane)")
    ((34 . 37) "Fog cloud (arcane)")
    ((38 . 39) "Ghoul touch (arcane)")
    (40 "Glide (arcane)")
    ((41 . 43) "Gust of wind (arcane)")
    ((44 . 46) "Haunting mists (arcane)")
    ((47 . 50) "Hideous laughter (arcane)")
    ((51 . 53) "Hypnotic pattern (arcane)")
    ((54 . 56) "Locate object (arcane)")
    ((57 . 59) "Make whole (arcane)")
    ((60 . 61) "Misdirection (arcane)")
    (62 "Obscure object (arcane)")
    ((63 . 64) "Pernicious poison (arcane)")
    ((65 . 66) "Protection from arrows (arcane)")
    ((67 . 69) "Pyrotechnics (arcane)")
    ((70 . 72) "Returning weapon (arcane)")
    ((73 . 76) "Scare (arcane)")
    ((77 . 79) "Shadow anchor (arcane)")
    ((80 . 82) "Share memory (arcane)")
    ((83 . 84) "Slipstream (arcane)")
    ((85 . 87) "Spectral hand (arcane)")
    ((88 . 89) "Spontaneous immolation (arcane)")
    ((90 . 92) "Touch od idiocy (arcane)")
    (93 "Unchakable chill (arcane)")
    ((94 . 95) "Magic mouth (arcane)")
    (96 "Arcane lock (arcane)")
    ((97 . 98) "Continual flame (arcane)")
    (99 "Phantom trap (arcane)")))

(defvar *UA-lvl-three-scroll*
  '(((0 . 2) "Animate dead (lesser) (arcane)")
    ((3 . 5) "Aqueous orb (arcane)")
    ((6 . 7) "Arcane sight (arcane)")
    ((8 . 11) "Beast shape (arcane)")
    ((12 . 14) "Clairaudience/clairvoyance (arcane)")
    ((15 . 16) "Cloak of winds (arcane)")
    ((17 . 19) "Daylight (arcane)")
    ((20 . 23) "Deep slumber (arcane)")
    ((24 . 26) "Distracting cacophony (arcane)")
    ((27 . 29) "Draconic reservoir (arcane)")
    ((30 . 34) "Elemental aura (arcane)")
    ((35 . 37) "Explosive runes (arcane)")
    ((38 . 42) "Force push (arcane)")
    ((43 . 44) "Gentle repose (arcane)")
    ((45 . 46) "Halt undead (arcane)")
    ((47 . 48) "Healing thief (arcane)")
    ((49 . 50) "Hydraulic torrent (arcane)")
    ((51 . 55) "Keen edge (arcane)")
    ((56 . 60) "Magic weapon (greater) (arcane)")
    ((62 . 64) "Monsterous physique I (arcane)")
    ((65 . 67) "Rage (arcane)")
    ((68 . 69) "Ray of Exhaustion (arcane)")
    ((70 . 72) "Resinous skin (arcane)")
    ((73 . 74) "Resist energy (communal) (arcane)")
    ((75 . 77) "Secret page (arcane)")
    ((78 . 79) "Shrink item (arcane)")
    ((80 . 82) "Sleet storm (arcane)")
    ((83 . 85) "Spiked pit (arcane)")
    ((86 . 89) "Undead autonomy I (arcane)")
    ((90 . 91) "Versitile weapon (arcane)")
    ((92 . 94) "Wind wall (arcane)")
    (95 "Illusort script (arcane)")
    ((96 . 98) "Nondetection (arcane)")
    (99 "Sepia snake sigil (arcane)")))

(defvar *UA-lvl-four-scroll*
  '(((0 . 1) "Acid pit (arcane)")
    ((2 . 5) "Arcane eye (arcane)")
    ((6 . 9) "Ball lighting (arcane)")
    ((10 . 12) "Contagion (arcane)")
    ((13 . 16) "Darkvision (greater) (arcane)")
    ((17 . 18) "Detect scrying (arcane)")
    ((19 . 22) "Dragon's breath (arcane)")
    ((23 . 27) "False life (greater) (arcane)")
    ((28 . 31) "Firefall (arcane)")
    ((32 . 34) "Geas (lesser) (arcane)")
    ((35 . 38) "Ghost wolf (arcane)")
    ((39 . 40) "Hallucinatory terrain (arcane)")
    ((41 . 42) "Illusory wall (arcane)")
    ((43 . 45) "Locate creature (arcane)")
    ((46 . 49) "Minor creation (arcane)")
    ((50 . 53) "Monstrous physique II (arcane)")
    ((54 . 56) "Obsidian flow (arcane)")
    ((57 . 58) "Phantom chariot (arcane)")
    ((59 . 61) "Rainbow pattern (arcane)")
    ((62 . 63) "Reduce person (mass) (arcane)")
    ((64 . 67) "Remove curse (arcane)")
    ((68 . 70) "Secure shelter (arcane)")
    ((71 . 73) "Shadow projection (arcane)")
    ((74 . 78) "Shocking image (arcane)")
    ((79 . 82) "Telekinetic charge (arcane)")
    ((83 . 84) "True form (arcane)")
    ((85 . 88) "Vermin shape I (arcane)")
    ((89 . 93) "Volcanic storm (arcane)")
    ((94 . 96) "Wandering star motes (arcane)")
    ((97 . 98) "Fire trap (arcane)")
    (99 "Mnemonic enhancer (arcane)")))

(defvar *UA-lvl-five-scroll*)

(defvar *UA-lvl-six-scroll*)

(defvar *UA-lvl-seven-scroll*)

(defvar *UA-lvl-eight-scroll*)

(defvar *UA-lvl-nine-scroll*)

;Common Devine

(defvar *CD-lvl-zero-scroll*
  '(((0 . 10) "Bleed (devine)")
    ((11 . 20) "Create water (devine)")
    ((21 . 33) "Detect magic (devine)")
    ((34 . 43) "Know direction (devine)")
    ((44 . 54) "Light (devine)")
    ((55 . 64) "Mending (devine)")
    ((65 . 74) "Purify food/drink (devine)")
    ((75 . 87) "Read magic (devine)")
    ((88 . 99) "Stabilize (devine)")))

(defvar *CD-lvl-one-scroll*
  '(((0 . 3) "Bane (devine)")
    ((4 . 9) "Bless (devine)")
    ((10 . 14) "Cause fear (devine)")
    ((15 . 18) "Command (devine)")
    ((19 . 21) "Comprehend languages (devine)")
    ((22 . 27) "Cure light wounds (devine)")
    ((28 . 29) "Detect chaos (devine)")
    ((30 . 31) "Detect evil (devine)")
    ((32 . 33) "Detect good (devine)")
    ((34 . 35) "Detect law (devine)")
    ((36 . 38) "Detect undead (devine)")
    ((39 . 44) "Divine favor (devine)")
    ((45 . 47) "DOOM! (devine)")
    ((48 . 51) "Entangle (devine)")
    ((52 . 56) "Inflict light wounds (devine)")
    ((57 . 60) "Magic fang (devine)")
    ((61 . 64) "Obscuring mist (devine)")
    ((65 . 67) "Produce flame (devine)")
    ((68 . 70) "Protection from chaos (devine)")
    ((71 . 73) "Protection from evil (devine)")
    ((74 . 76) "Protection from good (devine)")
    ((77 . 79) "Protection from law (devine)")
    ((80 . 83) "Remove fear (devine)")
    ((84 . 87) "Sanctuary (devine)")
    ((88 . 93) "Shield of faith (devine)")
    ((94 . 96) "Summon monster I (devine)")
    ((97 . 99) "Summon nature's ally I (devine)")))

(defvar *CD-lvl-two-scroll
  '(((0 . 3) "Aid (devine)")
    ((4 . 5) "Alighn weapon (devine)")
    ((6 . 7) "Animal messenger (devine)")
    ((8 . 12) "Barkskin (devine)")
    ((13 . 15) "Bear's endurance (devine)")
    ((16 . 18) "Bull's strength (devine)")
    ((19 . 21) "Cat's grace (devine)")
    ((22 . 23) "Chill metal (devine)")
    ((24 . 29) "Cure moderate wounds (devine)")
    ((30 . 32) "Darkness (devine)")
    ((33 . 35) "Delay poison (devine)")
    ((36 . 38) "Eagle's splendor (devine)")
    ((39 . 40) "Find traps (devine)")
    ((41 . 43) "Flame blade (devine)")
    ((44 . 45) "Fog cloud (devine)")
    ((46 . 49) "Heat metal (devine)")
    ((50 . 51) "Hold animal (devine)")
    ((52 . 55) "Hold person (devine)")
    ((56 . 59) "Inflict moderate wounds (devine)")
    ((60 . 62) "Owl's wisdom (devine)")
    ((63 . 64) "Remove paralysis (devine)")
    ((65 . 67) "Resist energy (devine)")
    ((68 . 72) "Restoration (lesser) (devine)")
    ((73 . 76) "Shield other (devine)")
    ((77 . 80) "Silence (devine)")
    ((81 . 84) "Sound burst (devine)")
    ((85 . 88) "Spiritual weapon (devine)")
    ((89 . 90) "Summon monster II (devine)")
    ((91 . 92) "Summon nature's ally II (devine)")
    ((93 . 94) "Summon swarm (devine)")
    ((95 . 96) "Zone of truth (devine)")
    ((97 . 99) "Augury (devine)")))

(defvar *CD-lvl-three-scroll*
  '(((0 . 2) "Bestow curse (devine)")
    ((3 . 7) "Call lightning (devine)")
    ((8 . 14) "Cure serious wounds (devine)")
    ((15 . 18) "Daylight (devine)")
    ((19 . 22) "Deeper darkness (devine)")
    ((23 . 27) "Dispell magic (devine)")
    ((28 . 32) "Inflict serious wounds (devine)")
    ((33 . 36) "Invisibility purge (devine)")
    ((37 . 39) "Locate object (devine)")
    ((40 . 41) "Magic circle against chaos (devine)")
    ((42 . 43) "Magic circle against evil (devine)")
    ((44 . 45) "Magic circle against good (devine)")
    ((46 . 47) "Magic circle against law (devine)")
    ((48 . 51) "Magic fang (greater) (devine)")
    ((52 . 56) "Magic vestment (devine)")
    ((57 . 58) "Poison (devine)")
    ((59 . 64) "Player (devine)")
    ((65 . 67) "Protection from energy (devine)")
    ((68 . 69) "Remove blindness/deafness (devine)")
    ((70 . 72) "Remove curse (devine)")
    ((73 . 75) "Remove disease (devine)")
    ((76 . 78) "Searing light (devine)")
    ((79 . 80) "Sleet storm (devine)")
    ((81 . 84) "Speak with dead (devine)")
    ((85 . 86) "Stone shape (devine)")
    ((87 . 88) "Summon monster III (devine)")
    ((89 . 90) "Summon nature's ally III (devine)")
    ((91 . 94) "Water breathing (devine)")
    ((95 . 96) "Water walk (devine)")
    ((97 . 99) "Animate dead (devine)")))

(defvar *CD-lvl-four-scroll*)

(defvar *CD-lvl-five-scroll*)

(defvar *CD-lvl-six-scroll*)

(defvar *CD-lvl-seven-scroll*)

(defvar *CD-lvl-eight-scroll*)

(defvar *CD-lvl-nine-scroll*)

;Uncommon Devine

(defvar *UD-lvl-zero-scroll*
  '(((0 . 14) "Detect poison (devine)")
    ((15 . 32) "Flare (devine)")
    ((33 . 49) "Guidance (devine)")
    ((50 . 67) "Resistance (devine)")
    ((68 . 84) "Spark (devine)")
    ((85 . 99) "Virtue (devine)")))

(defvar *UD-lvl-one-scroll*
  '(((0 . 3) "Ant haul (devine)")
    ((4 . 6) "Aspect of the falcon (devine)")
    ((7 . 8) "Calm animals (devine)")
    ((9 . 11) "Charm animal (devine)")
    ((12 . 14) "Compel hostility (devine)")
    ((15 . 16) "Deathwatch (devine)")
    (17 "Detect animals or plants (devine)")
    ((18 . 19) "Detect snares/pits (devine)")
    ((20 . 22) "Diagnose disease (devine)")
    ((23 . 26) "Endure elements (devine)")
    ((27 . 29) "Entropic shield (devine)")
    ((30 . 32) "Faerie fire (devine)")
    ((33 . 35) "Feather step (devine)")
    ((36 . 38) "Forbid action (devine)")
    ((39 . 41) "Frostbite (devine)")
    ((42 . 45) "Goodberry (devine)")
    (46 "Hide from animals (devine)")
    ((47 . 48) "Hide from undead (devine)")
    ((49 . 51) "Hydraulic push (devine)")
    ((52 . 54) "Jump (devine)")
    ((55 . 58) "Keen senses (devine)")
    ((59 . 61) "Liberating command (devine)")
    ((62 . 64) "Longstrider (devine)")
    ((65 . 67) "Magic stone (devine)")
    ((68 . 71) "Pass without trace (devine)")
    ((72 . 73) "Remove sickness (devine)")
    (74 "Sanctify corpse (devine)")
    ((75 . 77) "Shillelagh (devine)")
    ((78 . 80) "Speak with animals (devine)")
    ((81 . 84) "Stone fist (devine)")
    ((85 . 87) "Stone shield (devine)")
    ((88 . 90) "Sun metal (devine)")
    ((91 . 94) "Touch of the sea (devine)")
    ((95 . 97) "Bless water (devine)")
    ((98 . 99) "Curse water (devine)")))
;
(defvar *UD-lvl-two-scroll*
  '(((0 . 3) "Animal aspect (devine)")
    ((4 .  5) "Animal trance (devine)")
    ((6 . 9) "Animate dead (lesser) (devine)")
    ((10 . 12) "Arrow of law (devine)")
    ((13 . 16) "Aspect of the bear (devine)")
    ((17 . 19) "Blessing of courage and life (devine)")
    ((20 . 23) "Calm emotions (devine)")
    ((24 . 26) "Death knell (devine)")
    ((27 . 29) "Dread bolt (devine)")
    ((30 . 33) "Effortless armor (devine)")
    ((34 . 36) "Enthrall (devine)")
    ((37 . 40) "Flaming sphere (devine)")
    ((41 . 42) "Gentle repose (devine)")
    ((43 . 45) "Grace (devine)")
    ((46 . 47) "Groundswell (devine)")
    ((48 . 50) "Gust of wind (devine)")
    ((51 . 52) "Instant armor (devine)")
    ((53 . 54) "Instrument of agony (devine)")
    ((55 . 57) "Make whole (devine)")
    ((58 . 59) "Reduce animal (devine)")
    ((60 . 61) "Scent trail (devine)")
    ((62 . 64) "Shard of chaos (devine)")
    ((65 . 67) "Share language (devine)")
    ((68 . 69) "Shatter (devine)")
    ((70 . 72) "Soften earth and stone (devine)")
    ((73 . 75) "Spear of purity (devine)")
    ((76 . 78) "Spider climb (devine)")
    ((79 . 81) "Status (devine)")
    ((82 . 83) "Tree shape (devine)")
    (84 "Undetectable alignment (devine)")
    ((85 . 87) "Warp wood (devine)")
    ((88 . 90) "Weapon of awe (devine)")
    ((91 . 92) "Wood shape (devine)")
    ((93 . 94) "Consecrate (devine)")
    ((95 . 96) "Desecrate (devine)")
    ((97 . 98) "Fire trap (devine)")
    (99 "Masterwork transformation (devine)")))
;
(defvar *UD-lvl-three-scroll*
  '(((0 . 3) "Aqueous orb (devine)")
    ((4 . 7) "Archon's aura (devine)")
    ((8 . 11) "Bestow insight (devine)")
    ((12 . 15) "Blindness/deafness (devine)")
    ((16 . 18) "Burst of nettles (devine)")
    ((19 . 21) "Chain of perdition (devine)")
    ((22 . 25) "Contagion (devine)")
    ((24 . 29) "Create food/water (devine)")
    ((30 . 33) "Daybreak arrow (devine)")
    ((34 . 35) "Diminsih plants (devine)")
    ((36 . 39) "Discovery torch (devine)")
    ((40 . 44) "Dominate animal (devine)")
    ((45 . 47) "Guiding star (devine)")
    ((48 . 50) "Helping hand (devine)")
    ((51 . 55) "Meld into stone (devine)")
    ((56 . 57) "Obscure object (devine)")
    ((58 . 60) "Plant growth (devine)")
    ((61 . 63) "Quench (devine)")
    ((64 . 66) "Shifting sands (devine)")
    ((67 . 71) "Snare (devine)")
    ((72 . 74) "Speak with plants (devine)")
    ((75 . 79) "Spike growth (devine)")
    ((80 . 82) "Vision of hell (devine)")
    ((83 . 86) "Wind wall (devine)")
    ((87 . 89) "Wrathful mantle (devine)")
    ((90 . 92) "Continual flame (devine)")
    ((93 . 95) "Nap stack (devine)")
    ((96 . 97) "Glyph of warding (devine)")
    ((98 . 99) "Symbol of healing (devine)")))

(defvar *UD-lvl-four-scroll*)

(defvar *UD-lvl-five-scroll*)

(defvar *UD-lvl-six-scroll*)

(defvar *UD-lvl-seven-scroll*)

(defvar *UD-lvl-eight-scroll*)

(defvar *UD-lvl-nine-scroll*)
