(in-package :treasure-gen)

(defvar *lesser-medium-staff*
  '(((0 . 9) "Staff of blessed relief")
    ((10 . 19) "Staff of minor arcana")
    ((20 . 29) "Staff of tricks")
    ((30 . 43) "Staff of the scout")
    ((44 . 53) "Staff of eidolons")
    ((54 . 66) "Staff of accompaniment")
    ((67 . 83) "Staff of understanding")
    ((84 . 99) "Staff of charming")))

(defvar *greater-medium-staff*
  '(((0 . 10) "Staff of fire")
    ((11 . 20) "Staff of courage")
    ((21 . 28) "Staff of belittling")
    ((29 . 37) "Staff of feast and famine")
    ((38 . 48) "Staff of rigor")
    ((49 . 59) "Staff of swarming insects")
    ((60 . 67) "Staff of authority")
    ((68 . 80) "Staff of radiance")
    ((81 . 91) "Staff of size alteration")
    ((92 . 99) "Staff of Journeys")))

(defvar *lesser-major-staff*
  '(((0 . 3) "Staff of acid")
    ((4 . 7) "Staff of shrieking")
    ((8 . 10) "Chaotic staff")
    ((11 . 13) "Holy staff")
    ((14 . 16) "Lawful staff")
    ((17 . 20) "Staff of healing")
    ((21 . 23) "Unholy staff")
    ((24 . 27) "Staff of the master")
    ((28 . 31) "Staff of spiders")
    ((32 . 35) "Staff of electricity")
    ((36 . 38) "Heretic’s bane")
    ((39 . 41) "Musical staff")
    ((42 . 45) "Staff of souls")
    ((46 . 49) "Staff of toxins")
    ((50 . 53) "Staff of stealth")
    ((54 . 57) "Staff of the avenger")
    ((58 . 61) "Staff of aspects")
    ((62 . 65) "Staff of speaking")
    ((66 . 69) "Staff of frost")
    ((70 . 73) "Staff of bolstering")
    ((74 . 77) "Staff of curses")
    ((78 . 84) "Staff of dark flame")
    ((85 . 88) "Staff of cackling wrath")
    ((89 . 92) "Staff of performance")
    ((93 . 96) "Animate staff")
    ((97 . 99) "Staff of revelations")))

(defvar *greater-major-staff*
  '(((0 . 3) "Staff of illumination")
    ((4 . 6) "Staff of obstacles")
    ((7 . 9) "Staff of heaven and earth")
    ((10 . 12) "Staff of travel")
    ((13 . 15) "Staff of hoarding")
    ((16 . 18) "Staff of traps")
    ((19 . 21) "Staff of many rays")
    ((22 . 24) "Staff of mithral might")
    ((25 . 28) "Staff of defense")
    ((29 . 31) "Staff of the planes")
    ((32 . 34) "Staff of hungry shadows")
    ((35 . 37) "Dragon staff")
    ((38 . 40) "Staff of slumber")
    ((41 . 45) "Staff of abjuration")
    ((46 . 50) "Staff of conjuration")
    ((51 . 55) "Staff of divination")
    ((56 . 60) "Staff of enchantment")
    ((61 . 65) "Staff of evocation")
    ((66 . 70) "Staff of illusion")
    ((71 . 75) "Staff of necromancy")
    ((76 . 80) "Staff of transmutation")
    ((81 . 82) "Staff of weather")
    ((83 . 85) "Staff of earth and stone")
    ((86 . 87) "Staff of vision")
    ((88 . 90) "Staff of the woodlands")
    ((91 . 93) "Staff of life")
    (94 "Staff of one hundred hands")
    ((95 . 97) "Staff of passage")
    (98 "Staff of the hierophant")
    (99 "Staff of power")))
