(in-package :treasure-gen)

;The way we find where everything else is!

(defvar *lesser-minor-wonderous*
  '(((0 . 5) *lesser-minor-belt*)
    ((6 . 11) *lesser-minor-body*)
    ((12 . 16) *lesser-minor-chest*)
    ((17 . 21) *lesser-minor-eyes*)
    ((22 . 27) *lesser-minor-feet*)
    ((28 . 33) *lesser-minor-hands*)
    ((34 . 40) *lesser-minor-head*)
    ((41 . 46) *lesser-minor-headband*)
    ((47 . 53) *lesser-minor-neck*)
    ((54 . 60) *lesser-minor-shoulder*)
    ((61 . 66) *lesser-minor-wrist*)
    ((67 . 99) *lesser-minor-slotless*)))
;
(defvar *greater-minor-wonderous*
  '(((0 . 5) *greater-minor-belt*)
    ((6 . 11) *greater-minor-body*)
    ((12 . 16) *greater-minor-chest*)
    ((17 . 21) *greater-minor-eyes*)
    ((22 . 27) *greater-minor-feet*)
    ((28 . 33) *greater-minor-hands*)
    ((34 . 40) *greater-minor-head*)
    ((41 . 46) *greater-minor-headband*)
    ((47 . 53) *greater-minor-neck*)
    ((54 . 60) *greater-minor-shoulder*)
    ((61 . 66) *greater-minor-wrist*)
    ((67 . 99) *greater-minor-slotless*)))

(defvar *lesser-medium-wonderous*
  '(((0 . 5) *lesser-medium-belt*)
    ((6 . 11) *lesser-medium-body*)
    ((12 . 16) *lesser-medium-chest*)
    ((17 . 21) *lesser-medium-eyes*)
    ((22 . 27) *lesser-medium-feet*)
    ((28 . 33) *lesser-medium-hands*)
    ((34 . 40) *lesser-medium-head*)
    ((41 . 46) *lesser-medium-headband*)
    ((47 . 53) *lesser-medium-neck*)
    ((54 . 60) *lesser-medium-shoulder*)
    ((61 . 66) *lesser-medium-wrist*)
    ((67 . 99) *lesser-medium-slotless*)))

(defvar *greater-medium-wonderous*
  '(((0 . 5) *greater-medium-belt*)
    ((6 . 11) *greater-medium-body*)
    ((12 . 16) *greater-medium-chest*)
    ((17 . 21) *greater-medium-eyes*)
    ((22 . 27) *greater-medium-feet*)
    ((28 . 33) *greater-medium-hands*)
    ((34 . 40) *greater-medium-head*)
    ((41 . 46) *greater-medium-headband*)
    ((47 . 53) *greater-medium-neck*)
    ((54 . 60) *greater-medium-shoulder*)
    ((61 . 66) *greater-medium-wrist*)
    ((67 . 99) *greater-medium-slotless*)))

(defvar *lesser-major-wonderous*
  '(((0 . 5) *lesser-major-belt*)
    ((6 . 11) *lesser-major-body*)
    ((12 . 16) *lesser-major-chest*)
    ((17 . 21) *lesser-major-eyes*)
    ((22 . 27) *lesser-major-feet*)
    ((28 . 33) *lesser-major-hands*)
    ((34 . 40) *lesser-major-head*)
    ((41 . 46) *lesser-major-headband*)
    ((47 . 53) *lesser-major-neck*)
    ((54 . 60) *lesser-major-shoulder*)
    ((61 . 66) *lesser-major-wrist*)
    ((67 . 99) *lesser-major-slotless*)))

(defvar *greater-major-wonderous*
  '(((0 . 5) *greater-major-belt*)
    ((6 . 11) *greater-major-body*)
    ((12 . 16) *greater-major-chest*)
    ((17 . 21) *greater-major-eyes*)
    ((22 . 27) *greater-major-feet*)
    ((28 . 33) *greater-major-hands*)
    ((34 . 40) *greater-major-head*)
    ((41 . 46) *greater-major-headband*)
    ((47 . 53) *greater-major-neck*)
    ((54 . 60) *greater-major-shoulder*)
    ((61 . 66) *greater-major-wrist*)
    ((67 . 99) *greater-major-slotless*)))

;Least stuff, wat do?

(defvar *least-minor-slotless*
  '((0 "Feather token (anchor)")
    (1 "Universal solvent")
    ((2 . 3) "Ioun torch")
    (4 "Stubborn nail")
    (5 "War paint of the terrible visage")
    (6 "Elixir of love")
    (7 "Unguent of timelessness")
    (8 "Feather token (fan)")
    (9 "Formula alembic")
    (10 "Hybridization funnel")
    (11 "Soul soap")
    (12 "Dust of tracelessness")
    ((13 . 15) "Elixir of hiding")
    ((16 . 18) "Elixir of swimming")
    ((19 . 21) "Elixir of tumbling")
    ((22 . 24) "Elixir of vision")
    ((25 . 26) "Nightdrops")
    (27 "Oil of silence")
    ((28 . 30) "Silversheen")
    (31 "Traveler's any-tool")
    ((32 . 33) "Bottle of messages")
    ((34 . 35) "Feather token (bird)")
    (36 "Origami swarm")
    (37 "Alluring golden apple")
    (38 "Feather token (tree)")
    (39 "Key of lock jamming")
    ((40 . 41) "Feather token (swan boat)")
    (42 "Animated portrait")
    (43 "Bottled misfortune")
    ((44 . 45) "Elixir of truth")
    ((46 . 47) "Feather token (whip)")
    ((48 . 50) "Scabbard of honing")
    ((51 . 52) "Seer's tea")
    ((53 . 56) "Abjurant salt")
    ((57 . 60) "Arrow magnet")
    ((61 . 62) "Dust of darkness")
    ((63 . 68) "Campfire bead")
    ((69 . 71) "Archon's torch")
    ((72 . 74) "Book of extended summoning (lesser)")
    ((75 . 78) "Iron rope")
    ((79 . 82) "Snapleaf")
    ((83 . 85) "Bottled yeti fur")
    ((86 . 88) "Defoliant polish")
    ((89 . 91) "Dust of emulation")
    ((92 . 96) "Steadfast gut-stone")
    ((97 . 99) "Dust of dryness")))

;belt! They do on ya waist

(defvar *lesser-minor-belt*
  '(((0 . 15) "Belt of tumbling")
    ((16 . 27) "Beneficial bandolier")
    ((28 . 39) "Meridian belt")
    ((40 . 53) "Bladed belt")
    ((54 . 69) "Heavyload belt")
    ((70 . 83) "Aquatic cummerbund")
    ((84 . 99) "Equestrian belt")))
;
(defvar *greater-minor-belt*
  '(((0 . 17) "Belt of giant strength +2")
    ((18 . 35) "Belt of incredible dexterity +2")
    ((36 . 53) "Belt of mighty constitution +2")
    ((54 . 61) "Belt of teeth")
    ((62 . 73) "Blinkback belt")
    ((74 . 83) "Plague rat belt")
    ((84 . 99) "Belt of foraging")))

(defvar *lesser-medium-belt*
  '(((0 . 3) "Serpent belt")
    ((4 . 7) "Monkey belt")
    ((8 . 15) "Belt of physical might +2")
    ((16 . 21) "Belt of the weasel")
    ((22 . 26) "Belt of thunderous charging")
    ((27 . 31) "Minotaur belt")
    ((32 . 35) "Plague rat belt (greater)")
    ((36 . 40) "Belt of equilibrium")
    ((41 . 45) "Security belt")
    ((46 . 50) "Belt of mighty hurling (lesser)")
    ((51 . 56) "Belt of dwarvenkind")
    ((57 . 60) "Cord of stubborn resolve")
    ((61 . 70) "Belt of giant strength +4")
    ((71 . 79) "Belt of physical perfection +2")
    ((80 . 89) "Belt of incredible dexterity +4")
    ((90 . 99) "Belt of mighty constitution +4")))

(defvar *greater-medium-belt*
  '(((0 . 11) "Monkey belt (greater)")
    ((12 . 25) "Anaconda’s coils")
    ((26 . 37) "Serpent belt (greater)")
    ((38 . 52) "Belt of fallen heroes")
    ((53 . 66) "Gorgon belt")
    ((67 . 83) "Elemental earth belt")
    ((84 . 99) "Sash of flowing water")))

(defvar *lesser-major-belt*
  '(((0 . 11) "Merform belt")
    ((12 . 29) "Belt of giant strength +6")
    ((30 . 47) "Belt of incredible dexterity +6")
    ((48 . 65) "Belt of mighty constitution +6")
    ((66 . 87) "Belt of physical might +4")
    ((88 . 99) "Belt of mighty hurling (greater)")))

(defvar *greater-major-belt*
  '(((0 . 24) "Belt of stoneskin")
    ((25 . 54) "Belt of physical perfection +4")
    ((55 . 74) "Belt of physical might +6")
    ((75 . 89) "Shadowform belt")
    ((90 . 99) "Belt of physical perfection +6")))

;BODIES!

(defvar *lesser-minor-body*
  '(((0 . 19) "Robe of infinite twine")
    ((20 . 34) "Robe of needles")
    ((35 . 59) "Robe of bones")
    ((60 . 69) "Bodywrap of mighty strikes")
    ((70 . 79) "Corset of the vishkanya")
    ((80 . 99) "Druid's vestment")))
;
(defvar *greater-minor-body*
  '(((0 . 14) "Cassock of the clergy")
    ((15 . 29) "Mnemonic vestment")
    ((30 . 44) "Robe of components")
    ((45 . 59) "Sorcerer's robe")
    ((60 . 74) "Eidolon anchoring harness")
    ((75 . 99) "Robe of useful items")))

(defvar *lesser-medium-body*
  '(((0 . 14) "Robe of blending")
    ((15 . 25) "Blazing robes")
    ((26 . 36) "Shocking robe")
    ((37 . 47) "Voidfrost robes")
    ((48 . 58) "Bodywrap of mighty strikes +2")
    ((59 . 74) "Monk’s robe")
    ((75 . 99) "Robe of arcane heritage")))

(defvar *greater-medium-body*
  '(((0 . 24) "Xorn robe")
    ((25 . 51) "Corset of dire witchcraft")
    ((52 . 75) "Bodywrap of mighty strikes +3")
    ((76 . 99) "Robe of scintillating colors")))

(defvar *lesser-major-body*
  '(((0 . 39) "Gunman’s duster")
    ((40 . 79) "Bodywrap of mighty strikes +4")
    ((80 . 99) "Smuggler’s collapsible robe")))

(defvar *greater-major-body*
  '(((0 . 9) "Robe of stars")
    ((10 . 14) "Robe of gates")
    ((15 . 19) "Otherworldly kimono")
    ((20 . 39) "Bodywrap of mighty strikes +5")
    ((40 . 50) "Resplendent robe of the thespian")
    ((51 . 66) "Robe of the archmagi")
    ((67 . 76) "Bodywrap of mighty strikes +6")
    ((77 . 96) "Robe of eyes")
    ((97 . 99) "Bodywrap of mighty strikes +7")))

;Chests! No not that kind

(defvar *lesser-minor-chest*
  '(((0 . 14) "Bandages of rapid recovery")
    ((15 . 29) "Quick runner's shirt")
    ((30 . 49) "Endless bandolier")
    ((50 . 74) "All tools vest")
    ((75 . 99) "Vest of surgery")))
;
(defvar *greater-minor-chest*
  '(((0 . 9) "Sash of the war champion")
    ((10 . 19) "Sipping jacket")
    ((20 . 30) "Tunic of careful casting")
    ((30 . 41) "Vest of escape")
    ((42 . 51) "Cackling hag's blouse")
    ((52 . 61) "Deadshot vest")
    ((62 . 69) "Prophet's pectoral")
    ((70 . 78) "Tunic of deadly might")
    ((79 . 89) "Vest of the vengful tracker")
    ((90 . 99) "Resplendent uniform")))

(defvar *lesser-medium-chest*
  '(((0 . 12) "Shirt of immolation")
    ((13 . 27) "Snakeskin tunic")
    ((28 . 39) "Bane baldric")
    ((40 . 59) "Unfettered shirt")
    ((60 . 79) "Poisoner’s jacket (lesser)")
    ((80 . 99) "Vest of the cockroach")))

(defvar *greater-medium-chest*
  '(((0 . 49) "Vest of stable mutation")
    ((50 . 99) "Spectral shroud")))

(defvar *lesser-major-chest*
  '(((0 . 59) "Mantle of immortality")
    ((60 . 99) "Poisoner’s jacket (greater)")))

(defvar *greater-major-chest*
  '(((0 . 34) "Merciful baldric")
    ((35 . 69) "Mantle of faith")
    ((70 . 99) "Mantle of spell resistance")))

;Eyes and other sight things

(defvar *lesser-minor-eyes*
  '(((0 . 17) "Deathwatch eyes")
    ((18 . 37) "Eyes of the eagle")
    ((38 . 57) "Goggles of minute seeing")
    ((58 . 71) "Pirate's eye patch")
    ((72 . 86) "Spectacles of understanding")
    ((87 . 99) "Lenses of detection")))
;
(defvar *greater-minor-eyes*
  '(((0 . 19) "Eyes of the owl")
    ((20 . 43) "Eyes of keen sight")
    ((44 . 65) "Treasure hunter's goggles")
    ((66 . 83) "Inquisitor's nomocle")
    ((84 . 99) "Kinsight goggles")))

(defvar *lesser-medium-eyes*
  '(((0 . 15) "Goggles of elvenkind")
    ((16 . 30) "Goggles of brilliant light")
    ((31 . 47) "Blind man’s fold")
    ((48 . 66) "Goggles of night")
    ((67 . 81) "Lenses of figment piercing")
    ((82 . 99) "Arachnid goggles")))

(defvar *greater-medium-eyes*
  '(((0 . 20) "Darklands goggles")
    ((21 . 39) "Sniper goggles")
    ((40 . 57) "Rainbow lenses")
    ((58 . 76) "Annihilation spectacles")
    ((77 . 99) "Eyes of doom")))

(defvar *lesser-major-eyes*
  '(((0 . 59) "Eyes of eyebite")
    ((60 . 99) "Sniper goggles (greater)")))

(defvar *greater-major-eyes*
  '(((0 . 17) "Eyes of charming")
    ((18 . 33) "Monocle of the investigator")
    ((34 . 47) "Sea tyrant’s patch")
    ((48 . 62) "Swordmaster’s blindfold")
    ((63 . 76) "Mindmaster’s eyes")
    ((77 . 89) "Eyes of the dragon")
    ((90 . 99) "Truesight goggles")))

;Shoes, socks, and weird not-flip flop things

(defvar *lesser-minor-feet*
  '(((0 . 10) "Boosts of the cat")
    ((11 . 21) "Daredevil boots")
    ((22 . 30) "Boots of the enduring march")
    ((31 . 40) "Feather step slippers")
    ((41 . 49) "Boots of friendly terrain")
    ((50 . 59) "Boots of the winterland")
    ((60 . 75) "Boots of elvenkind")
    ((76 . 84) "Acrobat slippers")
    ((85 . 91) "Horseshoes of speed")
    ((92 . 99) "Boots of the mire")))
;
(defvar *greater-minor-feet*
  '(((0 . 6) "Burglar boots (minor)")
    ((7 . 12) "Horseshoes of crushing blows +1")
    ((13 . 18) "Sandals of quick reaction")
    ((19 . 25) "Slippers of cloudwalking")
    ((26 . 39) "Slippers of spider climbing")
    ((40 . 45) "Sandals of the lightest step")
    ((46 . 59) "Boots of striding and springing")
    ((60 . 67) "Horseshoes of a zephyr")
    ((68 . 74) "Haunted shoes")
    ((75 . 81) "Jaunt boots")
    ((82 . 99) "Boots of levitation")))

(defvar *lesser-medium-feet*
  '(((0 . 7) "Boots of escape")
    ((8 . 13) "Earth root boots")
    ((14 . 20) "Nightmare boots")
    ((21 . 25) "Nightmare horseshoes")
    ((26 . 31) "Caltrop boots")
    ((32 . 38) "Tremor boots")
    ((39 . 46) "Boots of the mastodon")
    ((47 . 53) "Shoes of the lightning leaper")
    ((54 . 69) "Boots of speed")
    ((70 . 76) "Verdant boots")
    ((77 . 83) "Horseshoes of crushing blows +2")
    ((84 . 99) "Winged boots")))

(defvar *greater-medium-feet*
  '(((0 . 37) "Shoes of the firewalker")
    ((38 . 71) "Dryad sandals")
    ((72 . 99) "Horseshoes of the mist")))

(defvar *lesser-major-feet*
  '(((0 . 19) "Getaway boots")
    ((20 . 34) "Horseshoes of crushing blows +3")
    ((35 . 54) "Horseshoes of glory")
    ((55 . 74) "Burglar boots (major)")
    ((75 . 99) "Boots of teleportation")))

(defvar *greater-major-feet*
  '(((0 . 39) "Slippers of the triton")
    ((40 . 69) "Horseshoes of crushing blows +4")
    ((70 . 99) "Horseshoes of crushing blows +5")))

;Hands, gloves, finger wear

(defvar *lesser-minor-hands*
  '(((0 . 12) "Assisting gloves")
    ((13 . 21) "Claws of the ice bear")
    ((22 . 33) "Gloves of reconnaissance")
    ((34 . 45) "Glowing glove")
    ((46 . 57) "Apprentice's cheating gloves")
    ((58 . 69) "Challenger's gloves")
    ((70 . 79) "Gloves of larceny")
    ((80 . 89) "Healer's gloves")
    ((90 . 99) "Engineer's workgloves")))
;
(defvar *greater-minor-hands*
  '(((0 . 11) "Gauntlets of the skilled maneuver")
    ((12 . 20) "Ghostvision gloves")
    ((21 . 32) "Gloves of arrow snaring")
    ((33 . 42) "Trapspringer's gloves")
    ((43 . 54) "Gloves of arcane striking")
    ((55 . 64) "Poisoner's gloves")
    ((65 . 74) "Magnetist's gloves")
    ((75 . 99) "Gloves of swimming and climbing")))

(defvar *lesser-medium-hands*
  '(((0 . 1) "Deliquescent gloves")
    ((2 . 4) "Form-fixing gauntlets")
    ((5 . 7) "Iron cobra gauntlet")
    ((8 . 15) "Shadow falconer’s glove")
    ((16 . 19) "Spellstrike gloves")
    ((20 . 27) "Glyphbane gloves")
    ((28 . 39) "Glove of storing")
    ((40 . 45) "Gloves of shaping")
    ((46 . 53) "Pliant gloves")
    ((54 . 75) "Gauntlet of rust")
    ((76 . 99) "Gloves of dueling")))

(defvar *greater-medium-hands*
  '(((0 . 29) "Vampiric gloves")
    ((30 . 64) "Giant fist gauntlets")
    ((65 . 99) "Gloves of the shortened path")))

(defvar *lesser-major-hands*
  '(((0 . 39) "Gloves of the commanding conjurer")
    ((40 . 99) "Gauntlet of rust (greater)")))

(defvar *greater-major-hands*
  '(((0 . 59) "Talons of Leng")
    ((60 . 99) "Gauntlets of the weaponmaster")))

;Head, hats, wigs

(defvar *lesser-minor-head*
  '(((0 . 9) "Mask of stony demeanor")
    ((10 . 21) "Cap of human guise")
    ((22 . 35) "Cap of light")
    ((36 . 55) "Hat of disguise")
    ((56 . 70) "Buffering cap")
    ((71 . 84) "Miser's mask")
    ((85 . 99) "Stalker's mask")))
;
(defvar *greater-minor-head*
  '(((0 . 11) "Circlet of pursuasion")
    ((12 . 20) "Grappler's mask")
    ((21 . 30) "Helm of fearsome mien")
    ((31 . 39) "Jingasa of the fortunate soldier")
    ((40 . 53) "Helm of comprehend languages and read magic")
    ((54 . 66) "Crown of swords")
    ((67 . 86) "Crown of blasting (minor)")
    ((87 . 99) "Mask of the krenshar")))

(defvar *lesser-medium-head*
  '(((0 . 15) "Helm of the mammoth lord")
    ((16 . 29) "Veil of fleeting glances")
    ((30 . 45) "Mask of a thousand tomes")
    ((46 . 62) "Medusa mask")
    ((63 . 79) "Cap of the free thinker")
    ((80 . 99) "Halo of inner calm")))

(defvar *greater-medium-head*
  '(((0 . 5) "Cat’s eye crown")
    ((6 . 11) "Maw of the wyrm")
    ((12 . 18) "Mitre of the hierophant")
    ((19 . 26) "Magician’s hat")
    ((27 . 33) "Circlet of mindsight")
    ((34 . 41) "Mask of the skull")
    ((42 . 49) "Howling helm")
    ((50 . 61) "Crown of blasting (major)")
    ((62 . 71) "Helm of underwater action")
    ((72 . 78) "Crown of conquest")
    ((79 . 84) "Batrachian helm")
    ((85 . 93) "Helm of telepathy")
    ((94 . 99) "Plague mask")))

(defvar *lesser-major-head*
  '(((0 . 13) "Iron circlet of guarded souls")
    ((14 . 28) "Laurel of command")
    ((29 . 44) "Mask of giants (lesser)")
    ((45 . 60) "Steel-mind cap")
    ((61 . 77) "Stormlord’s helm")
    ((78 . 99) "Helm of brilliance (lesser)")))

(defvar *greater-major-head*
  '(((0 . 13) "Judge’s wig")
    ((14 . 38) "Helm of teleportation")
    ((39 . 54) "Halo of menace")
    ((55 . 67) "Mask of giants (greater)")
    ((68 . 82) "Helm of brilliance")
    ((83 . 91) "Helm of electric radiance")
    ((92 . 99) "Crown of heaven")))

;Headbands, circleets, and whatever a "phylactery" is

(defvar *lesser-minor-headband*
  '(((0 . 59) "Phylactery of faithfulness")
    ((60 . 99) "Deadman's headband")))
;
(defvar *greater-minor-headband*
  '(((0 . 8) "Headband of alluring charisma +2")
    ((9 . 17) "Headband of inspired wisdom +2")
    ((18 . 26) "Headband of vast intelligence +2")
    ((27 . 32) "Headband of aerial agility +2")
    ((33 . 38) "Shifter's headband +2")
    ((39 . 44) "Headband of ponderous recollection")
    ((45 . 50) "Headband of ki focus")
    ((51 . 57) "Headband of unshakable resolve")
    ((58 . 65) "Hollywreath band")
    ((66 . 73) "Headband of deathless devotion")
    ((74 . 81) "Phylactery of the shepherd")
    ((82 . 90) "Headband of intuition")
    ((91 . 99) "Headband of fortune's favor")))

(defvar *lesser-medium-headband*
  '(((0 . 5) "Headband of havoc")
    ((6 . 11) "Serpent’s band")
    ((12 . 19) "Headband of mental prowess +2")
    ((20 . 25) "Hunter’s band")
    ((26 . 33) "Phylactery of negative channeling")
    ((34 . 41) "Phylactery of positive channeling")
    ((42 . 47) "Veiled eye")
    ((48 . 53) "Band of the stalwart warrior")
    ((54 . 59) "Headband of ninjitsu")
    ((60 . 67) "Headband of alluring charisma +4")
    ((68 . 75) "Headband of inspired wisdom +4")
    ((76 . 84) "Headband of mental superiority +2")
    ((85 . 92) "Headband of vast intelligence +4")
    ((93 . 99) "Shifter’s headband +4")))

(defvar *greater-medium-headband*
  '(((0 . 29) "Headband of arcane energy")
    ((30 . 69) "Headband of counterspelling")
    ((70 . 99) "Headband of knucklebones")))

(defvar *lesser-major-headband*
  '(((0 . 8) "Soulbound eye")
    ((9 . 18) "Winter wolf headband")
    ((19 . 31) "Headband of alluring charisma +6")
    ((32 . 44) "Headband of inspired wisdom +6")
    ((45 . 57) "Headband of vast intelligence +6")
    ((58 . 65) "Shifter’s headband +6")
    ((66 . 80) "Headband of mental prowess +4")
    ((81 . 89) "Headband of seduction")
    ((90 . 99) "Headband of aerial agility +4")))

(defvar *greater-major-headband*
  '(((0 . 19) "Headband of mental resilience")
    ((20 . 49) "Headband of mental superiority +4")
    ((50 . 64) "Headband of aerial agility +6")
    ((65 . 84) "Headband of metal prowess +6")
    ((85 . 99) "Headband of mental superiority +6")))

;Neck, please don't choke yourself

(defvar *lesser-minor-neck*
  '(((0 . 9) "Hand of the mage")
    ((10 . 17) "Aegis of recovery")
    ((18 . 24) "Amulet of bullet protection +1")
    ((25 . 36) "Brooch of shielding")
    ((37 . 48) "Necklace of fireballs (T-1)")
    ((49 . 62) "Amulet of natural armor +1")
    ((63 . 71) "Golembane scarab")
    ((72 . 81) "Necklace of fireballs (T-2)")
    ((82 . 88) "Swarmbane clasp")
    ((89 . 94) "Mind sentinel medallion")
    ((95 . 99) "Mummer's ruff")))
;
(defvar *greater-minor-neck*
  '(((0 . 7) "Amulet of elemental strife")
    ((8 . 14) "Righteous fist amulet")
    ((15 . 25) "Amulet of mighty fists +1")
    ((26 . 35) "Necklace of fireballs (T-3)")
    ((36 . 46) "Necklace of fireballs (T-4)")
    ((47 . 54) "Stormlure")
    ((55 . 65) "Necklace of fireballs (T-5)")
    ((66 . 72) "Amulet of bullet protection +2")
    ((73 . 80) "Feychild necklace")
    ((81 . 88) "Carcanet of detention")
    ((89 . 99) "Periapt of health")))

(defvar *lesser-medium-neck*
  '(((0 . 7) "Amulet of natural armor +2")
    ((8 . 11) "Amulet of proof against petrification")
    ((12 . 14) "Everwake amulet")
    ((15 . 17) "Gravewatch pendant")
    ((18 . 22) "hand of glory")
    ((23 . 25) "Torc of lionheart fury")
    ((26 . 32) "Necklace of fireballs (type VI)")
    ((33 . 39) "Necklace of fireballs (type VII)")
    ((40 . 42) "Amulet of hidden strength")
    ((43 . 46) "Necklace of adaptation")
    ((47 . 50) "Amulet of spell cunning")
    ((51 . 53) "Collar of the true companion")
    ((54 . 57) "Frost fist amulet")
    ((58 . 62) "Crystal of healing hands")
    ((63 . 65) "Guardian gorget")
    ((66 . 72) "Medallion of thoughts")
    ((73 . 76) "Periapt of protection from curses")
    ((77 . 80) "Forge fist amulet")
    ((81 . 84) "Amulet of bullet protection +3")
    ((85 . 91) "Periapt of wound closure")
    ((92 . 94) "Necklace of ki serenity")
    ((95 . 97) "Brooch of amber sparks")
    ((98 . 99) "Symbol of sanguine protection")))

(defvar *greater-medium-neck*
  '(((0 . 14) "Amulet of natural armor +3")
    ((15 . 23) "Ampoule of false blood")
    ((24 . 34) "Amulet of magecraft")
    ((35 . 49) "Amulet of mighty fists +2")
    ((50 . 61) "Dragonfoe amulet")
    ((62 . 66) "Amulet of spell mastery")
    ((67 . 71) "Amulet of bullet protection +4")
    ((72 . 84) "Hand of stone")
    ((85 . 99) "Periapt of proof against poison")))

(defvar *lesser-major-neck*
  '(((0 . 17) "Amulet of natural armor +4")
    ((18 . 34) "Amulet of proof against detection and location")
    ((35 . 48) "Amulet of bullet protection +5")
    ((49 . 66) "Scarab of protection")
    ((67 . 81) "Necklace of netted stars")
    ((82 . 99) "Amulet of mighty fists +3")))

(defvar *greater-major-neck*
  '(((0 . 34) "Amulet of natural armor +5")
    ((35 . 59) "Amulet of mighty fists +4")
    ((60 . 84) "Amulet of the planes")
    ((85 . 99) "Amulet of mighty fists +5")))

;Shoulder. Capes, cloaks and other superhero motif items

(defvar *lesser-minor-shoulder*
  '(((0 . 5) "Catching cape")
    ((6 . 9) "Cloak of human guise")
    ((10 . 29) "Cloak of resistance +1")
    ((30 . 35) "Muleback cords")
    ((36 . 37) "Shawl of life-keeping")
    ((38 . 43) "Shield cloak")
    ((44 . 49) "Quickchange cloak")
    ((50 . 55) "Cowardly crouching cloak")
    ((56 . 73) "Cloak of elvenkind")
    ((74 . 79) "Cloak of the hedge wizard")
    ((80 . 84) "Cloak of fiery vanishing")
    ((85 . 93) "Cloak of fangs")
    ((94 . 96) "Pauldrons of the serpent")
    ((97 . 99) "Stonemist cloak")))
;
(defvar *greater-minor-shoulder*
  '(((0 . 25) "Cloak of resistance +2")
    ((26 . 37) "Cloak of the scuttling rat")
    (38 "Seafoam shawl")
    ((40 . 51) "Treeform cloak")
    ((52 . 73) "Eagle cape")
    ((74 . 93) "Cloak of the manta ray")
    ((94 . 99) "Hunter's cloak")))

(defvar *lesser-medium-shoulder*
  '(((0 . 19) "Cloak of resistance +3")
    ((20 . 21) "Cloak of the duskwalker")
    ((22 . 24) "Cocoon cloak")
    ((25 . 26) "Pauldrons of the bull")
    ((27 . 31) "Stone cloak (minor)")
    ((32 . 39) "Cape of the mountebank")
    ((40 . 44) "Pauldrons of the watchful lion")
    ((45 . 51) "Lion cloak")
    ((52 . 53) "Mantle of spores")
    ((54 . 58) "Cape of effulgent escape")
    ((59 . 68) "Cloak of arachnida")
    ((69 . 71) "Gunfighter’s poncho")
    ((72 . 73) "Tentacle cloak")
    ((74 . 75) "Demonspike pauldrons")
    ((76 . 77) "Comfort’s cloak")
    ((78 . 87) "Cloak of resistance +4")
    ((88 . 90) "Shawl of the crone")
    ((91 . 99) "Prestidigitator’s cloak")))

(defvar *greater-medium-shoulder*
  '(((0 . 11) "Stole of justice")
    ((12 . 23) "Jellyfish cape")
    ((24 . 31) "Cloak of the diplomat")
    ((32 . 43) "Slashing cloak")
    ((44 . 55) "Stone cloak (major)")
    ((56 . 67) "Cloak of displacement (minor)")
    ((68 . 87) "Cloak of resistance +5")
    ((88 . 99) "Cloak of the bat")))

(defvar *lesser-major-shoulder*
  '(((0 . 39) "Highwayman’s cape")
    ((40 . 59) "Juggernaut’s pauldrons")
    ((60 . 99) "Charlatan’s cape")))

(defvar *greater-major-shoulder*
  '(((0 . 14) "Cloak of displacement (major)")
    ((15 . 34) "Wings of flying")
    ((35 . 54) "Cloak of etherealness")
    ((55 . 79) "Wings of the gargoyle")
    ((80 . 99) "Wyvern cloak")))

;Wrists, braclets, bracERS, and cute friendship bands

(defvar *lesser-minor-wrist*
  '(((0 . 9) "Sleeves of many garments")
    ((10 . 19) "Armbands of the brawler")
    ((20 . 47) "Bracer's of armor +1")
    ((48 . 62) "Burglar's bracers")
    ((63 . 90) "Bracers of steadiness")
    ((91 . 95) "Manacles of cooperation")
    ((96 . 99) "Shackles of complaiance")))
;
(defvar *greater-minor-wrist*
  '(((0 . 26) "Bracers of armor +2")
    (27 "Bracers of falcon's aim")
    ((28 . 37) "Inquisitor's bastion vambraces")
    ((38 . 64) "Bracers of archery (lesser)")
    ((65 . 67) "Spellguard bracers")
    ((68 . 70) "Bonebreaker gauntlets")
    ((71 . 80) "Vambraces of defense")
    ((81 . 97) "Verdant vine")
    (98 "Longarm bracers")
    (99 "Bracers of the glib entertainer")))

(defvar *lesser-medium-wrist*
  '(((0 . 3) "Charm bracelet")
    ((4 . 7) "Duelist’s vambraces")
    ((8 . 12) "Merciful vambraces")
    ((13 . 17) "Vambraces of the tactician")
    ((18 . 42) "Bracers of armor +3")
    ((43 . 52) "Seducer’s bane")
    ((53 . 57) "Bracers of the avenging knight")
    ((58 . 62) "Arrowmaster’s bracers")
    ((63 . 72) "Vambraces of the genie (efreeti)")
    ((73 . 77) "Bracelet of bargaining")
    ((78 . 81) "Bracelet of mercy")
    ((82 . 85) "Bracers of the merciful knight")
    ((86 . 89) "Bracelet of second chances")
    ((90 . 98) "Bracers of armor +4")
    (99  "Shackles of durance vile")))

(defvar *greater-medium-wrist*
  '(((0 . 9) "Vambraces of the genie (djinni)")
    ((10 . 19) "Vambraces of the genie (marid)")
    ((20 . 29) "Vambraces of the genie (shaitan)")
    ((30 . 49) "Bracelet of friends")
    ((50 . 69) "Bracers of archery (greater)")
    ((70 . 89) "Bracers of armor +5")
    ((90 . 99) "Bracers of sworn vengeance")))

(defvar *lesser-major-wrist*
  '(((0 . 29) "Dimensional shackles")
    ((30 . 44) "Gauntlets of skill at arms")
    ((45 . 99) "Bracers of armor +6")))

(defvar *greater-major-wrist*
  '(((0 . 59) "Bracers of armor +7")
    ((60 . 99) "Bracers of armor +8")))

;Misc, either it can't be worn, or doesn't mess with other stuff when it is

(defvar *lesser-minor-slotless*
  '(((0 . 2) *least-minor-slotless*)
    (3 "Anatomy doll")
    (4 "Bead of newt prevention")
    (5 "Beast-bond brand")
    (6 "Bookplate of recall")
    ((7 . 8) "Boro bead I")
    (9 "Concealing pocket")
    (10 "Dowsing syrup")
    (11 "Incense of transcendence")
    ((12 . 13) "Page of spell knowledge I")
    ((14 . 16) "Pearl of power I")
    (17 "Preserving flask I")
    ((18 . 19) "Pyxes of redirected focus")
    ((20 . 21) "Salve of slipperiness")
    (22 "Wasp nest of swarming")
    ((23 . 25) "Elixer of fire breath")
    (26 "Grave salt")
    ((27 . 28) "Pipes of sewers")
    ((29 . 30) "Dust of illusion")
    ((31 . 32) "Goblin skull bomb")
    ((33 . 34) "Elixer of dragon breath")
    (35 "Bookmark of deception")
    (36 "Word bottle")
    (37 "Dust of acid cunsumption")
    ((38 . 39) "Dust of appearance")
    ((40 . 41) "Efficient quiver")
    (42 "Pipes of sounding")
    (43 "Scabbard of vigor")
    (44 "Agile alpenstock")
    (45 "Blood reservoir of physical prowess")
    (46 "Clamor box")
    (47 "Dry load powder horn")
    (48 "Goblin fire drum")
    ((49 . 50) "Handy haversack")
    ((51 . 52) "Horn of fog")
    (53 "Iron spike of safe passage")
    (54 "Knight's pennon (honor)")
    ((55 . 58) "Volatile vaporizer I")
    ((59 . 61) "Elemental gem")
    ((62 . 63) "Flying ointment")
    (64 "Sovereign glue")
    (65 "Apple of eternal sleep")
    ((66 . 67) "Bag of holding I")
    (68 "Candle of truth")
    (69 "Hexing doll")
    ((70 . 71) "Stone of alarm")
    (72 "Book of extended summoning (standard)")
    ((73 . 76) "Bead of force")
    (77 "Cauldron of brewing")
    ((78 . 79) "Chime of opening")
    (80 "Philter of love")
    ((81 . 85) "Rope of climbing")
    ((86 . 87) "Volatile vaporizer II")
    (88 "Shroud of disintegration")
    ((89 . 91) "Bag of tricks (gray)")
    ((92 . 94) "Dust of disappearance")
    (95 "Dust of weighty burdens")
    (96 "Noble's vigilant pillbox")
    ((97 . 98) "Figurine of wonderous power (silver raven)")
    (99 "Volatile vaporizer III")))
;
(defvar *greater-minor-slotless*
  '(((0) "Boro bead II")
    ((1) "Cautionary creance")
    ((2) "Escape ladder")
    ((3) "Far-reaching sight")
    ((4 . 5) "Ioun stone (clear spindle)")
    ((6) "Marvelous pigments")
    ((7 . 14) "Page of spell knowledge II")
    ((15 . 24) "Pearl of power II")
    (25 "Preserving flask II")
    (26 "Restorative ointment")
    ((27 . 29) "Stone salve")
    (30 "Wind-caller compass")
    (31 "Goblin fire drum (greater)")
    (32 "Knight's pennon (battle)")
    (33 "knight's pennon (parley)")
    (34 "Void dust")
    (35 "Incense of meditation")
    (36 "Admixture vial")
    ((37 . 50) "Bag of holding II")
    (51 "Bone razor")
    (52 "Horn of the huntsman")
    (53 "Insistent doorknocker")
    ((54 . 55) "Ioun stone (dusty rose prism)")
    (56 "Mallet of building")
    (57 "Polymorphic pouch")
    (58 "Scabbard of stanching")
    (59 "School of eyes")
    (60 "Sheath of bladestealth")
    (61 "stone of alliance")
    (62 "Summoning shackle")
    (63 "Eversmoking bottle")
    (64 "Sustaining spoon")
    (65 "Wind fan")
    (66 "Grim lantern")
    (67 "Coin of the untrodden road")
    (68 "Horn of battle clarity")
    (69 "Life link badge")
    (70 "Martyr's tear")
    (71 "Pipes of haunting")
    (72 " Rope of knots")
    (73 "Singing bell of striking")
    (74 "Stone familiar")
    (75 "Book of extended summoning (greater)")
    (76 "Dragonbone divination sticks")
    (77 "Horn of goodness/evil")
    (78 "Naga scale bindi")
    (79 "Bottle of shadows")
    (80 "Cape of bravado")
    ((81 . 82) "Instant bridge")
    (83 "Mirror of guarding reflections")
    (84 "Folding boat")
    ((85 . 86) "Bottle of air")
    ((87 . 93) "Bag of holding III")
    (94 "Balm of impish grace")
    (95 "Candle of clean air")
    (96 "Harp of champing")
    ((97 . 99) "Manual of war")))

(defvar *lesser-medium-slotless*
  '((0  "Chalice of poison weeping")
    (1 "Exorcist’s aspergillum")
    (2 "Golem manual (flesh)")
    (3 "Harp of shattering")
    (4 "Insignia of valor")
    (5 "Ioun stone (deep red sphere)")
    (6 "Ioun stone (incandescent blue sphere)")
    (7 "Ioun stone (pale blue rhomboid)")
    (8 "Ioun stone (pink and green sphere)")
    (9 "Ioun stone (pink rhomboid)")
    (10 "Ioun stone (scarlet and blue sphere)")
    (11 "Needles of fleshgraving")
    (12 "Restless lockpicks")
    (13 "Werewhistle")
    ((14 . 15) "Deck of illusions")
    (16 "Candle of invocation")
    ((17 . 18) "Bag of tricks (rust)")
    (19 "Boro bead (3rd)")
    (20 "Decanter of endless water")
    (21 "Loathsome mirror")
    ((22 . 24) "Page of spell knowledge (3rd)")
    ((25 . 30) "Pearl of Power (3rd)")
    (31 "Preserving flask (3rd)")
    (32 "Figurine of wondrous power (serpentine owl)")
    (33 "Strand of prayer beads (lesser)")
    ((34 . 37) "Bag of holding (type IV)")
    (38 "Boundary chalk")
    (39 "Chime of resounding silence")
    (40 "Construct channel brick")
    (41 "Doomharp")
    (42 " Drum of advance and retreat")
    (43 "Embalming thread")
    (44 "Eye of the void")
    (45 "Figurine of wondrous power (bronze griffon)")
    (46 "Figurine of wondrous power (ebony fly)")
    (47 "Figurine of wondrous power (slate spider)")
    (48 "Hourglass of last chances")
    ((49 . 50) "Ioun stone (dark blue rhomboid)")
    (51 "Ki mat")
    (52 "Lord’s banner (swiftness)")
    (53 "Malleable symbol")
    (54 "Migrus locker")
    (55 "Ornament of healing light")
    (56 "Prayer wheel of ethical strength")
    (57 "Stone horse (courser)")
    (58 "Summon-slave crystal")
    (59 "Treasurer’s seal")
    (60 "Black soul shard")
    (61 "Golem manual (clay)")
    (62 "Horsemaster’s saddle")
    (63 "Pipes of dissolution")
    (64 "Pipes of pain")
    (65 "Seeker’s sight")
    (66 "Blessed book")
    (67 "Waters of transfiguration")
    (68 "Gem of brightness")
    (69 "Harp of contagion")
    (70 "Lyre of building")
    (71 "Void pennant")
    (72 "Stone horse (destrier)")
    (73 "Book of the loremaster")
    (74 "Cauldron of plenty")
    (75 "Horn of judgment")
    (76 "Horn of the tritons")
    (77 "Pearl of the sirines")
    (78 "Figurine of wondrous power (onyx dog)")
    ((79 . 80) "Bag of tricks (tan)")
    (81 "Boro bead (4th)")
    (82 "Page of spell knowledge (4th)")
    ((83 . 86) "Pearl of Power (4th)")
    (87 "Preserving flask (4th)")
    ((88 . 90) "Scabbard of keen edges")
    ((91 . 92) "Figurine of wondrous power (golden lions)")
    ((93 . 94) "Chime of interruption")
    ((95 . 98) "Broom of flying")
    (99 "Figurine of wondrous power (marble elephant)")))

(defvar *greater-medium-slotless*
  '(((0 . 2) "Ioun stone (iridescent spindle")
    (3 "Orb of foul Abaddon")
    ((4 . 7) "Carpet of flying (5 ft. by 5 ft.)")
    (8 "Horn of antagonism")
    ((9 . 12) "Horn of blasting")
    ((13 . 16) "Ioun stone (pale lavender ellipsoid")
    ((17 . 20) "Ioun stone (pearly white spindle)")
    ((21 . 23) "Master’s perfect golden bell")
    ((24 . 26) "Necromancer’s athame")
    ((27 . 30) "Portable hole")
    ((31 . 34) "Stone of good luck")
    ((35 . 36) "Figurine of wondrous power (ivory goats)")
    ((37 . 39) "Rope of entanglement")
    ((40 . 41) "Golem manual (stone)")
    (42 "Orb of golden heaven")
    ((43 . 44) "Mattock of the titans")
    ((45 . 47) "Drinking horn of bottomless valor")
    ((48 . 50) "Boro bead (5th)")
    ((51 . 52) "Chaos emerald")
    ((53 . 56) "Page of spell knowledge (5th)")
    ((57 . 63) "Pearl of Power (5th)")
    ((64 . 66) "Preserving flask (5th)")
    ((67 . 68) "Maul of the titans")
    ((69 . 72) "Iron bands of binding")
    ((73 . 75) "Cube of frost resistance")
    ((76 . 79) "Manual of bodily health +1")
    ((80 . 83) "Manual of gainful exercise +1")
    ((84 . 87) "Manual of quickness of action +1")
    ((88 . 91) "Tome of clear thought +1")
    ((92 . 95) "Tome of leadership and influence +1")
    ((96 . 99) "Tome of understanding +1")))

(defvar *lesser-major-slotless*
  '(((0 . 3) "Figurine of wondrous power (obsidian steed)")
    ((4 . 6) "Cauldron of the dead")
    ((7 . 10) "Drums of panic")
    ((11 . 14) "Ioun stone (orange prism)")
    ((15 . 18) "Ioun stone (pale green prism)")
    ((19 . 22) "Lantern of revealing")
    ((23 . 26) "Racing broom of flying")
    ((27 . 30) "Cauldron of resurrection")
    ((31 . 35) "Carpet of flying (5 ft. by 10 ft.)")
    ((36 . 37) "Golem manual (iron)")
    ((38 . 39) "Boro bead (6th)")
    ((40 . 43) "Ioun stone (vibrant purple prism)")
    ((44 . 47) "Orb of utter chaos")
    ((48 . 49) "Page of spell knowledge (6th)")
    ((50 . 57) "Pearl of Power (6th")
    ((58 . 59) "Preserving flask (6th)")
    ((60 . 63) "Cauldron of flying")
    ((64 . 65) "Enmity fetish")
    ((66 . 68) "Ioun stone (lavender and green ellipsoid)")
    ((69 . 72) "Ring gates")
    ((73 . 76) "Cauldron of seeing")
    ((77 . 80) "Crystal ball")
    ((81 . 82) "Golem manual (stone guardian)")
    ((83 . 86) "Drums of haste")
    ((87 . 90) "Strand of prayer beads (standard)")
    ((91 . 93) "Orb of storms")
    ((94 . 95) "Page of spell knowledge (7th)")
    ((96 . 99) "Pearl of Power (7th)")))

(defvar *greater-major-slotless*
  '(((0 . 2) "Crystal ball with")
    ((3 . 4) "Horn of Valhalla")
    ((5 . 7) "Crystal ball with detect thoughts")
    (8 "Last leaves of the autumn dryad")
    ((9 . 10) "Instant fortress")
    ((11 . 14) "Manual of bodily health +2")
    ((15 . 18) "Manual of gainful exercise +2")
    ((19 . 22) "Manual of quickness of action +2")
    ((23 . 26) "Tome of clear thought +2")
    ((27 . 30) "Tome of leadership and influence +2")
    ((31 . 34) "Tome of understanding +2")
    (35 "Lord’s banner (terror)")
    (36 "Carpet of flying (10 ft. by 10 ft.)")
    ((37 . 38) "Darkskull")
    (39 "Orb of pure law")
    (40 "Cube of force")
    ((41 . 42) "Page of spell knowledge (8th)")
    ((43 . 48) "Pearl of Power (8th)")
    (49 "Crystal ball with telepathy")
    (50 "Horn of blasting (greater)")
    ((51 . 53) "Pearl of Power (two spells)")
    (54 "Gem of seeing")
    (55 "Lord’s banner (victory)")
    (56 "Crystal ball with true seeing")
    ((57 . 58) "Page of spell knowledge (9th)")
    ((59 . 61) "Pearl of Power (9th)")
    (62 "Well of many worlds")
    ((63 . 64) "Manual of bodily health +3")
    ((65 . 66) "Manual of gainful exercise +3")
    ((67 . 68) "Manual of quickness of action +3")
    ((69 . 70) "Tome of clear thought +3")
    ((71 . 72) "Tome of leadership and influence +3")
    ((73 . 74) "Tome of understanding +3")
    (75 "Apparatus of the crab")
    (76 "Bowl of conjuring water elementals")
    (77 "Brazier of conjuring fire elementals")
    (78 "Censer of conjuring air elementals")
    (79 "Stone of conjuring earth elementals")
    (80 "Mirror of opposition")
    (81 "Strand of prayer beads (greater)")
    (82 "	Lord's banner (crusades)")
    (83 "Manual of bodily health +4")
    (84 "Manual of gainful exercise +4")
    (85 "Manual of quickness of action +4")
    (86 "Tome of clear thought +4")
    (87 "Tome of leadership and influence +4")
    (88 "Tome of understanding +4")
    (89 "Manual of bodily health +5")
    (90 "Manual of gainful exercise +5")
    (91 "Manual of quickness of action +5")
    (92 "Tome of clear thought +5")
    (93 "	Tome of leadership and influence +5")
    (94 "	Tome of understanding +5")
    (95 "Efreeti bottle")
    (96 "	Cubic gate")
    (97 "	Iron flask")
    (98 "Mirror of mental prowess")
    (99 "	Mirror of life trapping")))
