;The way we find where everything else is!
(defvar *lesser-minor-wonderous*
  '(((0 . 5) *lesser-minor-belts*)
    ((6 . 11) *lesser-minor-body*)
    ((12 . 16) *lesser-minor-chest*)
    ((17 . 21) *lesser-minor-eyes*)
    ((22 . 27) *lesser-minor-feet*)
    ((28 . 33) *lesser-minor-hands*)
    ((34 . 40) *lesser-minor-head*)
    ((41 . 46) *lesser-minor-headband*)
    ((47 . 53) *lesser-minor-neck*)
    ((54 . 60) *lesser-minor-shoulder*)
    ((61 . 66) *lesser-minor-wrist*)
    ((67 . 99) *lesser-minor-slotless*)))
;
(defvar *greater-minor-wonderous*
  '(((0 . 5) *greater-minor-belts*)
    ((6 . 11) *greater-minor-body*)
    ((12 . 16) *greater-minor-chest*)
    ((17 . 21) *greater-minor-eyes*)
    ((22 . 27) *greater-minor-feet*)
    ((28 . 33) *greater-minor-hands*)
    ((34 . 40) *greater-minor-head*)
    ((41 . 46) *greater-minor-headband*)
    ((47 . 53) *greater-minor-neck*)
    ((54 . 60) *greater-minor-shoulder*)
    ((61 . 66) *greater-minor-wrist*)
    ((67 . 99) *greater-minor-slotless*)))
;Least stuff, wat do?
(defvar *least-minor-slotless*
  '((0 "Feather token (anchor)")
    (1 "Universal solvent")
    ((2 . 3) "Ioun torch")
    (4 "Stubborn nail")
    (5 "War paint of the terrible visage")
    (6 "Elixir of love")
    (7 "Unguent of timelessness")
    (8 "Feather token (fan)")
    (9 "Formula alembic")
    (10 "Hybridization funnel")
    (11 "Soul soap")
    (12 "Dust of tracelessness")
    ((13 . 15) "Elixir of hiding")
    ((16 . 18) "Elixir of swimming")
    ((19 . 21) "Elixir of tumbling")
    ((22 . 24) "Elixir of vision")
    ((25 . 26) "Nightdrops")
    (27 "Oil of silence")
    ((28 . 30) "Silversheen")
    (31 "Traveler's any-tool")
    ((32 . 33) "Bottle of messages")
    ((34 . 35) "Feather token (bird)")
    (36 "Origami swarm")
    (37 "Alluring golden apple")
    (38 "Feather token (tree)")
    (39 "Key of lock jamming")
    ((40 . 41) "Feather token (swan boat)")
    (42 "Animated portrait")
    (43 "Bottled misfortune")
    ((44 . 45) "Elixir of truth")
    ((46 . 47) "Feather token (whip)")
    ((48 . 50) "Scabbard of honing")
    ((51 . 52) "Seer's tea")
    ((53 . 56) "Abjurant salt")
    ((57 . 60) "Arrow magnet")
    ((61 . 62) "Dust of darkness")
    ((63 . 68) "Campfire bead")
    ((69 . 71) "Archon's torch")
    ((72 . 74) "Book of extended summoning (lesser)")
    ((75 . 78) "Iron rope")
    ((79 . 82) "Snapleaf")
    ((83 . 85) "Bottled yeti fur")
    ((86 . 88) "Defoliant polish")
    ((89 . 91) "Dust of emulation")
    ((92 . 96) "Steadfast gut-stone")
    ((97 . 99) "Dust of dryness")))
;BELTS! They do on ya waist
(defvar *lesser-minor-belts*
  '(((0 . 15) "Belt of tumbling")
    ((16 . 27) "Beneficial bandolier")
    ((28 . 39) "Meridian belt")
    ((40 . 53) "Bladed belt")
    ((54 . 69) "Heavyload belt")
    ((70 . 83) "Aquatic cummerbund")
    ((84 . 99) "Equestrian belt")))
;
(defvar *greater-minor-belts*
  '(((0 . 17) "Belt of giant strength +2")
    ((18 . 35) "Belt of incredible dexterity +2")
    ((36 . 53) "Belt of mighty constitution +2")
    ((54 . 61) "Belt of teeth")
    ((62 . 73) "Blinkback belt")
    ((74 . 83) "Plague rat belt")
    ((84 . 99) "Belt of foraging")))
;BODIES!
(defvar *lesser-minor-body*
  '(((0 . 19) "Robe of infinite twine")
    ((20 . 34) "Robe of needles")
    ((35 . 59) "Robe of bones")
    ((60 . 69) "Bodywrap of mighty strikes")
    ((70 . 79) "Corset of the vishkanya")
    ((80 . 99) "Druid's vestment")))
;
(defvar *greater-minor-body*
  '(((0 . 14) "Cassock of the clergy")
    ((15 . 29) "Mnemonic vestment")
    ((30 . 44) "Robe of components")
    ((45 . 59) "Sorcerer's robe")
    ((60 . 74) "Eidolon anchoring harness")
    ((75 . 99) "Robe of useful items")))

; Chests! No not that kind
(defvar *lesser-minor-chest*
  '(((0 . 14) "Bandages of rapid recovery")
    ((15 . 29) "Quick runner's shirt")
    ((30 . 49) "Endless bandolier")
    ((50 . 74) "All tools vest")
    ((75 . 99) "Vest of surgery")))

;
(defvar *greater-minor-chest*
  '(((0 . 9) "Sash of the war champion")
    ((10 . 19) "Sipping jacket")
    ((20 . 30) "Tunic of careful casting")
    ((30 . 41) "Vest of escape")
    ((42 . 51) "Cackling hag's blouse")
    ((52 . 61) "Deadshot vest")
    ((62 . 69) "Prophet's pectoral")
    ((70 . 78) "Tunic of deadly might")
    ((79 . 89) "Vest of the vengful tracker")
    ((90 . 99) "Resplendent uniform")))

;Eyes and other sight things
(defvar *lesser-minor-eyes*
  '(((0 . 17) "Deathwatch eyes")
    ((18 . 37) "Eyes of the eagle")
    ((38 . 57) "Goggles of minute seeing")
    ((58 . 71) "Pirate's eye patch")
    ((72 . 86) "Spectacles of understanding")
    ((87 . 99) "Lenses of detection")))
;
(defvar *greater-minor-eyes*
  '(((0 . 19) "Eyes of the owl")
    ((20 . 43) "Eyes of keen sight")
    ((44 . 65) "Treasure hunter's goggles")
    ((66 . 83) "Inquisitor's nomocle")
    ((84 . 99) "Kinsight goggles")))

;Shoes, socks, and weird not-flip flop things
(defvar *lesser-minor-feet*
  '(((0 . 10) "Boosts of the cat")
    ((11 . 21) "Daredevil boots")
    ((22 . 30) "Boots of the enduring march")
    ((31 . 40) "Feather step slippers")
    ((41 . 49) "Boots of friendly terrain")
    ((50 . 59) "Boots of the winterland")
    ((60 . 75) "Boots of elvenkind")
    ((76 . 84) "Acrobat slippers")
    ((85 . 91) "Horseshoes of speed")
    ((92 . 99) "Boots of the mire")))
;
(defvar *greater-minor-feet*
  '(((0 . 6) "Burglar boots (minor)")
    ((7 . 12) "Horseshoes of crushing blows +1")
    ((13 . 18) "Sandals of quick reaction")
    ((19 . 25) "Slippers of cloudwalking")
    ((26 . 39) "Slippers of spider climbing")
    ((40 . 45) "Sandals of the lightest step")
    ((46 . 59) "Boots of striding and springing")
    ((60 . 67) "Horseshoes of a zephyr")
    ((68 . 74) "Haunted shoes")
    ((75 . 81) "Jaunt boots")
    ((82 . 99) "Boots of levitation")))
;Hands, gloves, finger wear
(defvar *lesser-minor-hands*
  '(((0 . 12) "Assisting gloves")
    ((13 . 21) "Claws of the ice bear")
    ((22 . 33) "Gloves of reconnaissance")
    ((34 . 45) "Glowing glove")
    ((46 . 57) "Apprentice's cheating gloves")
    ((58 . 69) "Challenger's gloves")
    ((70 . 79) "Gloves of larceny")
    ((80 . 89) "Healer's gloves")
    ((90 . 99) "Engineer's workgloves")))
;
(defvar *greater-minor-hands*
  '(((0 . 11) "Gauntlets of the skilled maneuver")
    ((12 . 20) "Ghostvision gloves")
    ((21 . 32) "Gloves of arrow snaring")
    ((33 . 42) "Trapspringer's gloves")
    ((43 . 54) "Gloves of arcane striking")
    ((55 . 64) "Poisoner's gloves")
    ((65 . 74) "Magnetist's gloves")
    ((75 . 99) "Gloves of swimming and climbing")))
;Head, hats, wigs
(defvar *lesser-minor-head*
  '(((0 . 9) "Mask of stony demeanor")
    ((10 . 21) "Cap of human guise")
    ((22 . 35) "Cap of light")
    ((36 . 55) "Hat of disguise")
    ((56 . 70) "Buffering cap")
    ((71 . 84) "Miser's mask")
    ((85 . 99) "Stalker's mask")))
;
(defvar *greater-minor-head*
  '(((0 . 11) "Circlet of pursuasion")
    ((12 . 20) "Grappler's mask")
    ((21 . 30) "Helm of fearsome mien")
    ((31 . 39) "Jingasa of the fortunate soldier")
    ((40 . 53) "Helm of comprehend languages and read magic")
    ((54 . 66) "Crown of swords")
    ((67 . 86) "Crown of blasting (minor)")
    ((87 . 99) "Mask of the krenshar")))
;Headbands, circleets, and whatever a "phylactery" is
(defvar *lesser-minor-headband*
  '(((0 . 59) "Phylactery of faithfulness")
    ((60 . 99) "Deadman's headband")))
;
(defvar *greater-minor-headband*
  '(((0 . 8) "Headband of alluring charisma +2")
    ((9 . 17) "Headband of inspired wisdom +2")
    ((18 . 26) "Headband of vast intelligence +2")
    ((27 . 32) "Headband of aerial agility +2")
    ((33 . 38) "Shifter's headband +2")
    ((39 . 44) "Headband of ponderous recollection")
    ((45 . 50) "Headband of ki focus")
    ((51 . 57) "Headband of unshakable resolve")
    ((58 . 65) "Hollywreath band")
    ((66 . 73) "Headband of deathless devotion")
    ((74 . 81) "Phylactery of the shepherd")
    ((82 . 90) "Headband of intuition")
    ((91 . 99) "Headband of fortune's favor")))
;Neck, please don't choke yourself
(defvar *lesser-minor-neck*
  '(((0 . 9) "Hand of the mage")
    ((10 . 17) "Aegis of recovery")
    ((18 . 24) "Amulet of bullet protection +1")
    ((25 . 36) "Brooch of shielding")
    ((37 . 48) "Necklace of fireballs (T-1)")
    ((49 . 62) "Amulet of natural armor +1")
    ((63 . 71) "Golembane scarab")
    ((72 . 81) "Necklace of fireballs (T-2)")
    ((82 . 88) "Swarmbane clasp")
    ((89 . 94) "Mind sentinel medallion")
    ((95 . 99) "Mummer's ruff")))
;
(defvar *greater-minor-neck*
  '(((0 . 7) "Amulet of elemental strife")
    ((8 . 14) "Righteous fist amulet")
    ((15 . 25) "Amulet of mighty fists +1")
    ((26 . 35) "Necklace of fireballs (T-3)")
    ((36 . 46) "Necklace of fireballs (T-4)")
    ((47 . 54) "Stormlure")
    ((55 . 65) "Necklace of fireballs (T-5)")
    ((66 . 72) "Amulet of bullet protection +2")
    ((73 . 80) "Feychild necklace")
    ((81 . 88) "Carcanet of detention")
    ((89 . 99) "Periapt of health")))
;Shoulder. Capes, cloaks and other superhero motif items
(defvar *lesser-minor-shoulder*
  '(((0 . 5) "Catching cape")
    ((6 . 9) "Cloak of human guise")
    ((10 . 29) "Cloak of resistance +1")
    ((30 . 35) "Muleback cords")
    ((36 . 37) "Shawl of life-keeping")
    ((38 . 43) "Shield cloak")
    ((44 . 49) "Quickchange cloak")
    ((50 . 55) "Cowardly crouching cloak")
    ((56 . 73) "Cloak of elvenkind")
    ((74 . 79) "Cloak of the hedge wizard")
    ((80 . 84) "Cloak of fiery vanishing")
    ((85 . 93) "Cloak of fangs")
    ((94 . 96) "Pauldrons of the serpent")
    ((97 . 99) "Stonemist cloak")))
;
(defvar *greater-minor-shoulder*
  '(((0 . 25) "Cloak of resistance +2")
    ((26 . 37) "Cloak of the scuttling rat")
    (38 "Seafoam shawl")
    ((40 . 51) "Treeform cloak")
    ((52 . 73) "Eagle cape")
    ((74 . 93) "Cloak of the manta ray")
    ((94 . 99) "Hunter's cloak")))
;Wrists, braclets, bracERS, and cute friendship bands
(defvar *lesser-minor-wrist*
  '(((0 . 9) "Sleeves of many garments")
    ((10 . 19) "Armbands of the brawler")
    ((20 . 47) "Bracer's of armor +1")
    ((48 . 62) "Burglar's bracers")
    ((63 . 90) "Bracers of steadiness")
    ((91 . 95) "Manacles of cooperation")
    ((96 . 99) "Shackles of complaiance")))
;
(defvar *greater-minor-wrist*
  '(((0 . 26) "Bracers of armor +2")
    (27 "Bracers of falcon's aim")
    ((28 . 37) "Inquisitor's bastion vambraces")
    ((38 . 64) "Bracers of archery (lesser)")
    ((65 . 67) "Spellguard bracers")
    ((68 . 70) "Bonebreaker gauntlets")
    ((71 . 80) "Vambraces of defense")
    ((81 . 97) "Verdant vine")
    (98 "Longarm bracers")
    (99 "Bracers of the glib entertainer")))
;Misc, either it can't be worn, or doesn't mess with other stuff when it is
(defvar *lesser-minor-slotless*
  '(((0 . 2) *least-minor-slotless*)
    (3 "Anatomy doll")
    (4 "Bead of newt prevention")
    (5 "Beast-bond brand")
    (6 "Bookplate of recall")
    ((7 . 8) "Boro bead I")
    (9 "Concealing pocket")
    (10 "Dowsing syrup")
    (11 "Incense of transcendence")
    ((12 . 13) "Page of spell knowledge I")
    ((14 . 16) "Pearl of power I")
    (17 "Preserving flask I")
    ((18 . 19) "Pyxes of redirected focus")
    ((20 . 21) "Salve of slipperiness")
    (22 "Wasp nest of swarming")
    ((23 . 25) "Elixer of fire breath")
    (26 "Grave salt")
    ((27 . 28) "Pipes of sewers")
    ((29 . 30) "Dust of illusion")
    ((31 . 32) "Goblin skull bomb")
    ((33 . 34) "Elixer of dragon breath")
    (35 "Bookmark of deception")
    (36 "Word bottle")
    (37 "Dust of acid cunsumption")
    ((38 . 39) "Dust of appearance")
    ((40 . 41) "Efficient quiver")
    (42 "Pipes of sounding")
    (43 "Scabbard of vigor")
    (44 "Agile alpenstock")
    (45 "Blood reservoir of physical prowess")
    (46 "Clamor box")
    (47 "Dry load powder horn")
    (48 "Goblin fire drum")
    ((49 . 50) "Handy haversack")
    ((51 . 52) "Horn of fog")
    (53 "Iron spike of safe passage")
    (54 "Knight's pennon (honor)")
    ((55 . 58) "Volatile vaporizer I")
    ((59 . 61) "Elemental gem")
    ((62 . 63) "Flying ointment")
    (64 "Sovereign glue")
    (65 "Apple of eternal sleep")
    ((66 . 67) "Bag of holding I")
    (68 "Candle of truth")
    (69 "Hexing doll")
    ((70 . 71) "Stone of alarm")
    (72 "Book of extended summoning (standard)")
    ((73 . 76) "Bead of force")
    (77 "Cauldron of brewing")
    ((78 . 79) "Chime of opening")
    (80 "Philter of love")
    ((81 . 85) "Rope of climbing")
    ((86 . 87) "Volatile vaporizer II")
    (88 "Shroud of disintegration")
    ((89 . 91) "Bag of tricks (gray)")
    ((92 . 94) "Dust of disappearance")
    (95 "Dust of weighty burdens")
    (96 "Noble's vigilant pillbox")
    ((97 . 98) "Figurine of wonderous power (silver raven)")
    (99 "Volatile vaporizer III")))
;
(defvar *greater-minor-slotless*
  '((0 "Boro bead II")
    (1 "Cautionary creance")
    (2 "Escape ladder")
    (3 "Far-reaching sight")
    ((4 . 5) "Ioun stone (clear spindle)")
    (6 "Marvelous pigments")
    ((7 . 14) "Page of spell knowledge II")
    ((15 . 24) "Pearl of power II")
    (25 "Preserving flask II")
    (26 "Restorative ointment")
    ((27 . 29) "Stone salve")
    (30 "Wind-caller compass")
    (31 "Goblin fire drum (greater)")
    (32 "Knight's pennon (battle)")
    (33 "knight's pennon (parley)")
    (34 "Void dust")
    (35 "Incense of meditation")
    (36 "Admixture vial")
    ((37 . 50) "Bag of holding II")
    (51 "Bone razor")
    (52 "Horn of the huntsman")
    (53 "Insistent doorknocker")
    ((54 . 55) "Ioun stone (dusty rose prism)")
    (56 "Mallet of building")
    (57 "Polymorphic pouch")
    (58 "Scabbard of stanching")
    (59 "School of eyes")
    (60 "Sheath of bladestealth")
    (61 "stone of alliance")
    (62 "Summoning shackle")
    (63 "Eversmoking bottle")
    (64 "Sustaining spoon")
    (65 "Wind fan")
    (66 "Grim lantern")
    (67 "Coin of the untrodden road")
    (68 "Horn of battle clarity")
    (69 "Life link badge")
    (70 "Martyr's tear")
    (71 "Pipes of haunting")
    (72 " Rope of knots")
    (73 "Singing bell of striking")
    (74 "Stone familiar")
    (75 "Book of extended summoning (greater)")
    (76 "Dragonbone divination sticks")
    (77 "Horn of goodness/evil")
    (78 "Naga scale bindi")
    (79 "Bottle of shadows")
    (80 "Cape of bravado")
    ((81 . 82) "Instant bridge")
    (83 "Mirror of guarding reflections")
    (84 "Folding boat")
    ((85 . 86) "Bottle of air")
    ((87 . 93) "Bag of holding III")
    (94 "Balm of impish grace")
    (95 "Candle of clean air")
    (96 "Harp of champing")
    ((97 . 99) "Manual of war")))
